# Generated by Django 6.0.3 on 2026-05-06 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='recipient_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
