import { createContext, useContext, useState, useEffect } from 'react';

const LanguageContext = createContext();

export const translations = {
  fr: {
    // Nav / Sidebar
    Dashboard: 'Tableau de bord',
    Projects: 'Projets',
    Archive: 'Archive',
    Groups: 'Groupes',
    Students: 'Étudiants',
    Teachers: 'Enseignants',
    Admin: 'Administration',
    Users: 'Utilisateurs',
    Supervision: 'Encadrement',
    Juries: 'Jurys',
    MyProject: 'Mon Projet',
    Tasks: 'Tâches',
    Meetings: 'Réunions',
    Profile: 'Profil',
    Evaluations: 'Évaluations',
    Year: 'Année d\'étude',
    Settings: 'Paramètres',
    Logout: 'Déconnexion',
    Requests: 'Demandes',

    // Common phrases
    Search: 'Rechercher...',
    Save: 'Enregistrer',
    Cancel: 'Annuler',
    Delete: 'Supprimer',
    Edit: 'Modifier',
    Submit: 'Soumettre',
    Approve: 'Approuver',
    Reject: 'Refuser',
    status: 'Statut',
    Date: 'Date',
    Loading: 'Chargement...',
    Error: 'Erreur',
    Success: 'Succès',
    Confirm: 'Confirmer',

    // Home Page
    HomeTitle: 'Gérez vos projets académiques avec',
    HomeSubtitle: 'La plateforme tout-en-un pour les étudiants, les encadreurs et l\'administration de l\'ESI. Collaborez, codez et réussissez.',
    HomeBadge: '🎓 Plateforme universitaire',
    GetStarted: 'Commencer maintenant',
    LearnMore: 'En savoir plus',
    StatsActiveStudents: 'Étudiants actifs',
    StatsProjects: 'Projets gérés',
    StatsTeachers: 'Encadreurs',
    StatsUptime: 'Disponibilité',
    FeaturesTitle: 'Tout ce dont vous avez besoin',
    FeaturesSubtitle: 'Une suite complète d\'outils pour accompagner chaque étape de votre projet.',
    ReadyToStart: 'Prêt à commencer ?',
    ReadyToStartSub: 'Connectez-vous avec votre compte ESI pour accéder à votre espace.',
    LoginBtn: 'Se connecter',
    FooterText: 'ESI-GIT — École Supérieure d\'Informatique. Tous droits réservés.',
    Feature1Title: 'Gestion Git', Feature1Desc: 'Intégration native des dépôts Git pour chaque projet académique.',
    Feature2Title: 'Travail en Groupe', Feature2Desc: 'Créez et gérez vos groupes de projet facilement.',
    Feature3Title: 'Planification', Feature3Desc: 'Organisez des réunions avec l\'encadreur sans friction.',
    Feature4Title: 'Kanban Board', Feature4Desc: 'Suivez les tâches en temps réel avec un tableau Kanban intuitif.',
    Feature5Title: 'Suivi & Évaluation', Feature5Desc: 'Notation transparente et feedback structuré sur chaque livrable.',
    Feature6Title: 'Accès Sécurisé', Feature6Desc: 'Rôles distincts pour étudiants, encadreurs et administration.',

    // Extended Dashboard & Groups
    DashboardGreeting: 'Bonjour',
    TasksCompleted: 'Tâches complétées',
    PlannedMeetings: 'Réunions planifiées',
    OverallProgress: 'Avancement global',
    TeacherTasks: 'Tâches de l\'encadreur',
    ProjectProgress: 'Avancement du projet',
    InProgress: 'En progression',
    NotStarted: 'Pas encore démarré',
    RecentActivity: 'Activité récente',
    UpcomingDeadlines: 'Prochaines deadlines',
    MyGroup: 'Mon groupe',
    NoActivity: 'Aucune activité pour l\'instant',
    NoGroupDetails: 'Vous n\'avez pas encore de groupe',
    CreateJoinGroup: 'Créer / rejoindre un groupe',
    TaskOrigin: 'Origine des tâches',
    TaskStatus: 'État des tâches',
    Deliverables: 'Livrables',
    GroupTitle: 'Groupe',
    GroupSubtitle: 'Créez ou rejoignez un groupe de projet',
    CreateGroup: 'Créer',
    JoinGroup: 'Rejoindre',
    MyGroupTitle: 'Mon Groupe',
    MyGroupSub: 'Membres, rôles et dépôt de votre équipe',
    CurrentGroup: 'Groupe actuel',
    InviteCode: 'Code d\'invitation',
    Copy: 'Copier',
    Copied: 'Copié !',
    GithubRepo: 'Dépôt GitHub',
    Load: 'Charger',
    Open: 'Ouvrir',
    ChooseFile: 'Choisir un fichier',
    JuryAssigned: 'Jury Assigné',
    'JuryRoles.president': 'Président',
    'JuryRoles.examiner': 'Examinateur',
    'JuryRoles.supervisor': 'Encadreur',
    'JuryRoles.member': 'Membre',
    AssignJury: 'Assigner Jury',
    EditJury: 'Modifier Jury',
    NoJuryAssigned: 'Aucun jury assigné',
    WaitSupervisorValidation: 'Attente validation encadreur',
    ValidationRequestSub: 'Sélectionnez les membres du jury pour ce projet.',
    NoFile: 'Aucun document PDF uploadé',
    ProjectValidation: 'Validation du projet',
    SubmitProjectToSup: 'Soumettez votre projet à votre encadreur pour validation finale.',
    TeamMembers: 'Équipe',
    ChangeRole: 'Changer rôle',
    LeaveGroup: 'Quitter le groupe',

    // Teacher
    MyGroups: 'Mes groupes',
    GroupsSupervision: 'Groupes sous votre encadrement',
    NoGroupYet: 'Aucun groupe pour le moment.',
    ClickGroupDetails: 'Cliquez sur un groupe pour voir les détails',
    AllGroups: 'Tous les groupes',
    ValidationRequest: 'Demande de validation',
    ValidationRequestSub: 'Le groupe a soumis ce projet pour approbation finale. Veuillez vérifier les détails du projet et son dépôt GitHub avant de valider.',
    AssignTask: 'Assigner une tâche',
    ScheduleMeeting: 'Planifier une réunion',

    // Tasks Page
    TaskManagement: 'Gestion des tâches',
    TasksCompleted_Subtitle: 'tâches complétées',
    NewTask: 'Nouvelle tâche',
    GlobalProgress: 'Progression globale',
    DropHere: 'Déposer ici',
    CreateTask: 'Créer une tâche',
    TaskTitle: 'Titre de la tâche',
    Description: 'Description',
    Priority: 'Priorité',
    Column: 'Colonne',
    Tag: 'Tag / Catégorie',
    AssignMembers: 'Assigner des membres',
    High: 'Haute',
    Medium: 'Moyenne',
    Low: 'Basse',
    Todo: 'À faire',
    Hide: 'Masquer',
    Actions: 'Actions',
    Done: 'Terminé',
    InProgress_Short: 'En cours',

    // Teacher Groups
    SupervisionRequests: 'Demandes d\'encadrement',
    SupervisedGroups: 'Groupes Encadrés',
    NoPendingRequests: 'Aucune demande d\'encadrement en attente.',
    NoSupervisedGroups: 'Vous n\'avez aucun groupe encadré pour le moment.',
    ApproveRequest: 'Accepter',
    NewValidationRequest: 'Nouvelle demande de validation',
    NewValidationRequestSub: 'Ce groupe a soumis son projet pour validation finale.',
    LastCommits: 'Derniers Commits',
    Members: 'Membres du groupe',
    AssignTo: 'Assigner à',
    IfNoneSelected: 'Si aucun sélectionné → assignée à tous les membres',
    MeetingAutoAccepted: 'Les réunions planifiées par l\'encadreur sont automatiquement acceptées.',
    
    // Teacher Dashboard
    TeacherDashboard: 'Dashboard Encadreur',
    RealDataAnalytics: 'Analytiques calculées depuis les données réelles',
    SupervisedGroups_Stat: 'Groupes encadrés',
    ActiveGroups_Stat: 'Groupes actifs',
    AvgProgress_Stat: 'Avancement moyen',
    CompletionRate_Stat: 'Taux de complétion',
    PendingMeetings_Stat: 'Réunions en attente',
    PendingEvals_Stat: 'Évaluations en attente',
    ProgressByGroup: 'Avancement par groupe',
    TaskState: 'État des tâches',
    TasksByPriority: 'Tâches par priorité',
    NoGroups: 'Aucun groupe',
    FinalValidationRequests: 'Demandes de validation finale (Projets terminés)',
    ProjectSubmittedFinal: 'Projet soumis pour validation de fin d\'année',
    ValidateProject: 'Valider le projet',
    SendWithCorrections: 'Renvoyer avec corrections',

    // Jury
    DefenseJury: 'Jury de Soutenance',
    JuryParticipation: 'Soutenances auxquelles vous participez en tant que membre du jury',
    Assigned: 'Assignées',
    ToEvaluate: 'À évaluer',
    Evaluated: 'Évaluées',
    Scheduled: 'Planifiée',
    Evaluate: 'Évaluer',
    DefenseEvaluation: 'Évaluation du Jury',
    FinalGradeCalculated: 'Note finale calculée',
    EvaluationComments: 'Commentaires sur l\'évaluation',

    // Archive
    ArchiveTitle: 'Archive des Projets',
    ArchiveSubtitle: 'Projets de fin d\'études des années précédentes',
    AvgGrade: 'Moyenne',
    Mentions: 'Mentions',
    Years: 'Années',
    FilterBy: 'Filtrer par',
    CurrentSupervisor: 'Encadreur Actuel',
    ManageSupervision: 'Gérez l\'encadrement de votre projet PFE',
    RequestNewSupervisor: 'Solliciter un nouvel encadreur',
    NoSupervisorAssigned: 'Aucun encadreur assigné pour le moment.',
    PendingRequest: 'Demande en attente',
    PendingRequestMsg: 'Vous avez déjà une demande en cours. Vous devez attendre la réponse ou qu\'elle soit refusée avant d\'en envoyer une autre.',
    RequestHistory: 'Historique des demandes',
    NoRequestsSent: 'Aucune demande envoyée.',
    Blocked: 'Bloqué',
    Block: 'Bloquer',
    Unblock: 'Débloquer',
    CyclePrepa: 'Cycle Préparatoire',
    CycleSuperieur: 'Cycle Supérieur',
    Department: 'Département',
    Blocked: 'Bloqué',
    Accepted: 'Accepté',
    RequestSent: 'Demande envoyée !',
    SendRequest: 'Envoyer la demande',
    ConfirmSend: 'Confirmer l\'envoi',
    AccompanyingMessage: 'Message d\'accompagnement (Optionnel)',
    ExplainSubject: 'Expliquez brièvement votre sujet de PFE...',
    SearchByTeacherName: 'Rechercher par nom ou spécialité...',
    OfficialSupervisor: 'Encadreur officiel du projet',
    YearFilter: 'Année',
    Supervisor: 'Encadreur',
    All: 'Tous',
    Validated: 'Validé',

    // Admin
    AdminDashboard: 'Dashboard Admin',
    RealTimeAnalytics: 'Analytiques en temps réel — données calculées depuis la base',
    TotalStudents_Stat: 'Total étudiants',
    Teachers_Stat: 'Enseignants',
    ArchivedProjects_Stat: 'Projets archivés',
    AvgProgressBySupervisor: 'Avancement moyen par encadreur',
    WeightedAvgProgress: 'Progression moyenne pondérée',
    UserDistribution: 'Répartition utilisateurs',
    Admins: 'Admins',
    GroupsPerSpecialty: 'Groupes par spécialité',
    ProjectState: 'État des projets',
    TotalTasks_Stat: 'Total tâches',
    AssignedBySupervisor: 'Assignées par encadreur',
    CreatedByStudents: 'Créées par étudiants',
    OverallAverage: 'Moyenne générale',
    Mentions_Stat: 'Mentions',
    NoGroupAssigned: 'Aucun groupe encore assigné',

    // User Management
    UserManagement: 'Utilisateurs',
    AddUser: 'Ajouter utilisateur',
    EditUser: 'Modifier utilisateur',
    DeleteUser: 'Supprimer utilisateur',
    UserDetail: 'Détail utilisateur',
    Identity: 'Identité',
    StudentInfo: 'Informations étudiant',
    TeacherInfo: 'Informations enseignant',
    AssignStudent: 'Assigner étudiant',
    AvailableForSupervision: 'Disponible pour encadrement',
    Department: 'Département',
    TeachingSpecialty: 'Spécialité d\'enseignement',
    Displaying: 'Affichage de',
    To: 'à',
    Of: 'sur',
    ConfirmDeleteUser: 'Êtes-vous sûr de vouloir supprimer cet utilisateur ? Cette action est irréversible.',
    
    // Group Management (Admin)
    AssignJury: 'Assigner le jury',
    EditJury: 'Modifier le jury',
    JuryAssigned: 'Jury assigné',
    NoJuryAssigned: 'Aucun jury assigné pour ce groupe.',
    GroupDetail: 'Détail du groupe',
    TotalGroups_Stat: 'Total groupes',
    Active_Stat: 'Actif',
    NonApproved_Stat: 'Non approuvé',
    StudentsWithoutGroup: 'Étudiants sans groupe',
    CreateGroupTitle: 'Créer un nouveau groupe',
    ProjectTitle: 'Titre du projet',
    GroupCode: 'Code du groupe',
    GroupManagement: 'Gestion des groupes',
    AllStudentsInGroup: 'Tous les étudiants ont un groupe',
    JuryRoles: {
      president: 'Président',
      member: 'Examinateur',
      supervisor: 'Encadreur'
    },

    // Profil
    ProfileTitle: 'Profil',
    ProfileSubtitle: 'Vos informations personnelles',
    PersonalInfo: 'Informations personnelles',
    FullName: 'Nom complet',
    Email: 'Adresse e-mail',
    Specialty: 'Spécialité',
    Promotion: 'Promotion',
    L1: '1ère Année (L1)',
    L2: '2ème Année (L2)',
    L3: '3ème Année (L3)',
    M1: 'Master 1 (M1)',
    M2: 'Master 2 (M2)',
    AdminLock: '🔒 Les informations du profil sont gérées par l\'administration. Contactez votre gestionnaire pour toute modification.',
    SwitchToTeacher: 'Passer en mode Enseignant',
    SwitchToAdmin: 'Passer en mode Administrateur',
    BackToTop: 'Retour en haut',
    Notifications: 'Notifications',
    ActiveProjects: 'Projets actifs',
    SubmissionsThisMonth: 'Soumissions ce mois',
    AvgCompletionRate: 'Taux de complétion moyen',
    HideArchiveStudent: 'Masquer l\'Archive (Étudiants)',
    HideArchiveStudent_Desc: 'Les étudiants ne pourront plus voir l\'archive des projets.',
    HideJuryTeacher: 'Masquer les Jurys (Enseignants)',
    HideJuryTeacher_Desc: 'Les enseignants ne pourront plus accéder à l\'évaluation des jurys.',

    // Missing keys added
    GroupName: 'Nom du groupe',
    ProjectTheme: 'Thème du projet',
    Role: 'Rôle',
    StatusUpdated: 'Statut mis à jour',
    FirstName: 'Prénom',
    LastName: 'Nom de famille',
    AcademicYear: 'Année académique',
    Level: 'Niveau',
    Groups_Stat: 'Groupes',
    NoData: 'Aucune donnée disponible',
    ProjectType: 'Type de projet',
    ProjectDescription: 'Description du projet',
    CreateProject: 'Créer un projet',
    SupervisorAvailability: 'Disponibilité',
    Available: 'Disponible',
    Unavailable: 'Indisponible',
    PasswordChanged: 'Mot de passe modifié avec succès',
    PasswordError: 'Erreur lors du changement de mot de passe',
    OldPassword: 'Ancien mot de passe',
    NewPassword: 'Nouveau mot de passe',
    ConfirmPassword: 'Confirmer le mot de passe',
    ChangePassword: 'Changer le mot de passe',
    BlockUser: 'Bloquer',
    UnblockUser: 'Débloquer',
    ResetPassword: 'Réinitialiser le mot de passe',

    // Admin Analytics & Settings
    PlatformAnalytics: 'Analyses de la plateforme',
    ConsolidatedData: 'Données consolidées',
    ExportCSV: 'Exporter Rapport (CSV)',
    SuccessRate: 'Taux de réussite',
    StudentsAtRisk: 'Étudiants à risque',
    GradeTrends: 'Tendances des notes',
    StudentActivity: 'Activité des étudiants',
    NotationPatterns: 'Patterns de notation (Enseignants)',
    UsageTrends: 'Tendances d\'utilisation',
    AcademicYears: 'Années académiques',
    ActiveYear: 'Année active',
    ActivePromos: 'Promotions actives',
    AddPromo: 'Ajouter promotion',
    ChangeYearWarning: '⚠️ Changer l\'année active archivera automatiquement tous les projets en cours.',
    SpecialtiesThemes: 'Spécialités & Thèmes',
    GradingFormula: 'Formule de calcul des moyennes',
    FormulaList: 'Formules existantes',
    ActiveStatus: 'ACTIVE',
    VisibilityAccess: 'Visibilité & Accès',
    ShowArchiveStudents: 'Afficher l\'archive aux étudiants',
    ShowArchiveStudents_Desc: 'Permet aux étudiants de consulter les anciens projets.',
    NewFormula: 'Nouvelle formule',
    Expression: 'Expression',
    
    // Admin Users Extra
    NewPasswordOptional: 'Nouveau Password (optionnel)',
    LeaveEmptyNoChange: 'Laisser vide pour ne pas changer',
    Choose: 'Choisir',
    ImportUsers: 'Importer des utilisateurs',
    StaffMembers: 'Enseignants / Staff',
    AccountsCreated: 'Comptes créés avec succès',
    StaffNote: 'Note: Un utilisateur Staff peut être à la fois Enseignant et Admin.',
    DragDropFile: 'Glissez votre fichier ici',
    Browse: 'parcourir',
    ImportInProgress: 'Import en cours...',
    Imported: 'utilisateur(s) importé(s) !',
    RowsIgnored: 'ligne(s) ignorée(s)',
    Summary: 'Résumé',
    StudentList: 'Liste des étudiants',
    Grade: 'Note',

    // Student Dashboard (new)
    TaskProgress: 'Avancement des tâches',
    TasksDone: 'Tâches réalisées',
    NoOverdue: 'Aucun retard',
    OverdueTasks: 'tâche(s) en retard',
    FinalSubmission: 'Soumission finale',
    AttendanceRate: 'Taux de présence',
    Meetings_label: 'réunions',
    FinalGrade: 'Note finale',
    NextMeeting: 'Prochaine réunion',

    // Teacher Dashboard (new)
    TasksDoneByGroup: 'Tâches réalisées par groupe',
    PendingRequestsStat: 'Demandes en attente',
    GroupsToWatch: 'Groupes à surveiller',
    AllGroupsOnTrack: 'Tous les groupes sont sur la bonne voie',
    Tasks_label: 'Tâches',
    Health_label: 'Santé',
    Health_OnTrack: '🟢 OK',
    Health_Watch: '🟡 Veille',
    Health_AtRisk: '🔴 Risque',

    // Admin Dashboard (new)
    NoGroup_Stat: 'Sans groupe',
    PendingApprovals_Stat: 'Approbations en attente',
    DefenseReadiness: 'Préparation soutenances',
    DefenseSubtitle: 'Entonnoir global · projets actifs',
    ActiveProjects_label: 'Projets actifs',
    JuriesAssigned_label: 'Jurys assignés',
    DefensesScheduled_label: 'Soutenances planif.',
    Graded_label: 'Notés',
    ReadyToArchive_label: 'Prêts à archiver',
    ByLevel: 'Par niveau',
    Graded_count: 'notés',

    // Admin Analytics (new)
    FailRate: 'Taux d\'échec',

    // Admin Settings — PanelYears
    CloseYearAdvance: 'Clôturer l\'année & Avancer',
    CloseYearDesc: 'Archive tous les projets actifs et passe automatiquement à l\'année suivante. Cette action est irréversible.',
    ChangeYearTitle: 'Changer l\'année ?',
    ChangeYearMsg: 'Changer l\'année académique va ARCHIVER tous les projets actuels. Cette action est irréversible.',
    ChangeAndArchive: 'Changer & Archiver',
    PlatformConfig: 'Configuration plateforme',
    NeedHelp: 'Besoin d\'aide ?',
    HelpDesc: 'Consultez la documentation pour configurer les paramètres avancés de la plateforme.',

    // Admin Settings — PanelCategories
    SpecialtyAdded: 'Spécialité ajoutée',
    SpecialtyDeleted: 'Supprimée',
    AbbrevPlaceholder: 'Abréviation (ex: ISI)',
    FullNamePlaceholder: 'Nom complet (ex: Ing. Systèmes Informatiques)',

    // Admin Settings — PanelVisibility
    DeliverableVisible: 'Livrables visibles (étudiants)',
    DeliverableVisible_Desc: 'Les étudiants peuvent voir les livrables des projets archivés',
    JuryPageVisible: 'Activer la page jury (enseignants)',
    JuryPageVisible_Desc: 'Les enseignants peuvent accéder à la page d\'évaluation du jury',
    SystemEmail: 'Email système',
    SystemEmailDesc: 'Utilisé comme adresse d\'envoi pour les credentials, réinitialisations de mot de passe et notifications système',
    GroupLockDeadline: '🔒 Date limite de formation des groupes',
    GroupLockDeadlineDesc: 'À partir de cette date, tous les groupes seront automatiquement verrouillés (plus de join / leave / kick). Les étudiants sans groupe verront un message d\'accès fermé. Laissez vide pour désactiver le verrou automatique.',
    LockActiveFrom: '⚠️ Verrou actif à partir du',

    // Admin Settings — PanelGradingFormula
    Name: 'Nom',
    Optional: 'optionnel',
    Components: 'Composantes de la note',
    Coefficient: 'Coef.',
    Add: 'Ajouter',
    Reset: 'Réinitialiser',
    Active: 'ACTIVE',
    Activate: 'Activer',
    SavedFormulas: 'Formules enregistrées',
    NoFormulas: 'Aucune formule définie',
    Saved: 'Enregistré',
    fieldsRequired: 'Champs requis',

    // Admin Groupes — JuryScheduleModal
    JurySelected: 'sélectionnés',
    SupervisorMustBeInJury: '⚠️ L\'encadreur doit faire partie du jury.',
    ExactlyOnePresident: '⚠️ Exactement 1 président requis.',
    DefenseOptional: 'Soutenance (optionnel — peut être complété plus tard)',
    Date: 'Date',
    Time: 'Heure',
    Room: 'Salle',
    Department: 'Département',
    PastDateError: 'La date ne peut pas être dans le passé.',
    JuryComplete: '✅ Jury complet',
    DefenseScheduled: 'Soutenance planifiée',
    JuryMembersCount: 'membres jury',

    // Admin Groupes — GroupDetailModal
    Graded: 'Noté',
    DefenseTitle: 'Soutenance',
    NotScheduled: 'Non planifiée',
    Deliverables_title: 'Livrables',
    NoDeliverable: 'Aucun livrable soumis.',
    DownloadAll: '⬇ Tout télécharger',

    // Admin Groupes — EditGroupModal
    ModifyGroup: 'Modifier',
    MembersCount: 'Membres',
    GroupLeader: 'Chef',
    RemoveMember: 'Retirer',
    AddStudent: 'Ajouter un étudiant',
    NoStudentAvailable: 'Aucun étudiant sans groupe disponible pour ce niveau.',
    SupervisorSection: 'Encadreur',
    ChangeSupervisor: 'Changer l\'encadreur',
    ArchiveGroup: 'Archiver',

    // Admin Groupes — CreateGroupModal
    ProjectTypeLabel: 'Type de Projet *',
    TitleDefaultNote: '📌 Le titre du projet sera "temp" par défaut. Le chef de groupe pourra modifier le nom et le type du projet après création.',
    LeaveEmptyLater: 'Laissez vide pour laisser le groupe choisir plus tard.',
    NoResults: 'Aucun résultat',
    AllStudentsHaveGroup: 'Tous les étudiants ont un groupe',
    Approved_Stat: 'Approuvés',

    // Admin Groupes — ArchiveAllModal
    CloseArchiveProjects: 'Clôturer & archiver des projets',
    OnlyGradedArchivable: 'Seuls les projets notés peuvent être archivés.',
    FilterByLevel: 'Filtrer par niveau',
    GradedProjects: 'Projets notés',
    Archivable: 'archivables',
    UngradedProjects: 'Projets non notés',
    WontBeArchived: 'ne seront pas archivés',
    IrreversibleArchive: 'L\'archivage est irréversible. Les projets archivés ne peuvent plus être modifiés par les étudiants.',
    Continue: 'Continuer',
    Selected: 'sélectionné(s)',
    FinalConfirmation: 'Confirmation finale',
    ArchiveConfirmMsg: 'Vous allez archiver ces projets — cette action est irréversible.',
    TypeToConfirm: 'Tapez ARCHIVER pour confirmer :',
    TypeArchive: 'Tapez ARCHIVER',
    Back: 'Retour',
    ArchivingInProgress: 'Archivage en cours…',
    ArchiveNow: 'Archiver maintenant',
    SelectAll: 'Tout sélectionner',
    DeselectAll: 'Tout désélectionner',
    ArchiveAll: 'Archiver tout',
    AllTags: 'Tous les tags',
    AllLevels: 'Tous les niveaux',
    AllSupervisors: 'Tous les encadreurs',
    ActiveTag: 'Actif',
    ApprovedTag: 'Approuvé',
    GradedTag: 'Noté',
    ReadyForDefense: 'Prêt pour la soutenance',
    JuryOkDateMissing: '⏳ Jury ✓ — Date manquante',
    JuryRequired: '⏳ Jury requis',
    GradedScore: 'Noté —',

    // Admin Students
    StudentAssignments: 'Affectations des Étudiants',
    StudentAssignmentsSub: 'Visualisez et gérez le statut d\'adhésion des étudiants aux groupes.',
    WithGroup: 'Avec Groupe',
    WithoutGroup: 'Sans Groupe',
    NotAssigned: 'Non assigné',
    Project: 'Projet',
    Student: 'Étudiant',
    Previous: 'Précédent',
    Next: 'Suivant',

    // Admin Users
    ImportExcel: 'Importer Excel',
    FileLevel: 'NIVEAU DU FICHIER',
    ConfirmImport: 'Confirmer l\'import',
    Grades: 'Notes',
    AlreadyExists: 'Déjà existant — niveau mis à jour',
    PasswordSentByEmail: '✉️ Mot de passe envoyé par email',
    ExpectedColumns: '📋 Colonnes attendues :',
    ImportAnotherFile: '↩ Importer un autre fichier',
    DeleteSelection: 'Supprimer la sélection ?',
    ConfirmBulkDelete: 'Êtes-vous sûr de vouloir supprimer définitivement ces utilisateurs ?',
    BulkDeleted: 'utilisateurs supprimés',
    BulkDeleteError: 'Erreur lors de la suppression groupée',
    Dispo: '🟢 Dispo',
    Indispo: '🔴 Indispo',
    Roles: 'Rôle',
    AllLevels2: 'Tous les niveaux',
    ID_Matricule: 'ID / Matricule (National ID)',
    YearLabel1: '1ère Année (1CPI)',
    YearLabel2: '2ème Année (2CPI)',
    YearLabel3: '3ème Année (1CS / 3CS)',
    YearLabel4: '4ème Année (2CS / 4CS)',
    YearLabel5: '5ème Année (3CS / 5CS)',

    // Admin Archive
    ArchiveVisibleStudents: '🔓 Archive visible aux étudiants',
    ArchivHiddenStudents: '🔒 Archive masquée aux étudiants',
    ArchiveVisibilityNote: 'Cette option active/désactive l\'onglet Archive pour tous les étudiants.',
    AvgGrade_Stat: 'Moyenne',
    Mention: 'Mentions',
    Found: 'trouvés',
    NoDescription: 'Aucune description disponible.',
    ProjectPublic: 'Public',
    ProjectPrivate: 'Privé',
    ProjectVisibility: 'Visibilité du projet',
    ProjectVisibilityDesc: 'Rendre le projet visible (public) ou le masquer (privé).',
    ProjectHidden: 'Projet masqué — cliquer pour rendre public',
    ProjectPublicTitle: 'Projet public — cliquer pour masquer',
    DeleteConfirmation: 'Cette action est irréversible.',
    SearchSupervisor: 'Rechercher encadreur...',
    Technologies: 'TECHNOLOGIES (séparées par des virgules)',

    // Admin Dashboard
    NoUsersYet: 'Aucun utilisateur pour l\'instant.',
    NoGradesYet: 'Aucune note enregistrée',
    AvgNotesByTeacher: 'Notes moyennes — Enseignants',

    // Admin Notifications
    NotifSend: 'Send Notification',
    NotifSendLabel: 'Envoyer une notification',
    NotifTitle: 'Titre',
    NotifMessage: 'Message',
    NotifAudience_all: 'Tout le monde',
    NotifAudience_students: 'Étudiants',
    NotifAudience_staff: 'Enseignants / Staff',
    NotifLevelOptional: 'Niveau (optionnel)',
    NotifSpecialtyOptional: 'Spécialité (optionnel)',
    AllSpecialties: 'Toutes les spécialités',
    NotifHistory: 'Notifications envoyées',
    NotifNoHistory: 'Aucune notification envoyée.',
    Refresh: 'Actualiser',
    Sending: 'Envoi en cours…',
    SendNotification: 'Envoyer la notification',
    NotifTitleRequired: 'Titre et message requis.',
    NotifSentSuccess: 'Notification envoyée',
    NotifDeleteFail: 'Échec de la suppression',
    NotifSendFail: 'Échec de l\'envoi',
    NotifDeleted: 'Supprimée',

    // Admin Profil
    CurrentPassword: 'Mot de passe actuel',
    Departement: 'Département',
    Specialite: 'Spécialité',

    // Teacher Meetings
    PendingMeetings: 'En attente',
    UpcomingMeetings: 'À venir',
    PastCancelledMeetings: 'Passées / annulées',
    AllGroups2: 'Tous les groupes',
    NoMeetings: 'Aucune réunion pour l\'instant',
    ApproveMeeting: '✓ Approuver',
    RejectMeeting: '✕ Refuser',
    CancelMeeting: 'Annuler',
    Attendances: '📋 Présences',
    CancellationReason: 'Motif d\'annulation :',
    AttendancesTitle: 'Présences',
    CheckPresentMembers: 'Cochez les membres présents',
    NoMembersFound: 'Aucun membre trouvé',
    SavingAttendance: 'Enregistrement…',
    SaveAttendance: 'Enregistrer',
    CancelConfirmTitle: 'Confirmer l\'annulation',
    CancelReasonPlaceholder: 'Motif d\'annulation (optionnel)...',
    AttendanceSaved: 'Présences enregistrées',
    AttendanceSaveError: 'Erreur lors de l\'enregistrement',
    CancelError: 'Erreur lors de l\'annulation',
    LoadAttendanceError: 'Impossible de charger les présences',
    MeetingStatusPending: 'En attente',
    MeetingStatusApproved: 'Planifiée',
    MeetingStatusRejected: 'Refusée',
    MeetingStatusCancelled: 'Annulée',

    // Teacher Groups
    Encadreur: 'Encadreur',
    NoRepo: 'Aucun dépôt renseigné par le groupe.',
    DownloadAllDocs: '⬇ Tout télécharger',
    NotAvailable: 'Non disponible',
    Open2: 'Ouvrir',
    GroupMembers: 'membre(s)',
    NoDocuments: 'Aucun document joint.',
    ProjectDocs: 'Documents du projet',
    ProjectApproved: 'Projet approuvé',
    Deadline: 'Deadline',

    // Admin Dashboard labels
    Pending_label: 'En attente',
    Approved_label: 'Approuvés',
    Archived_label: 'Archivés',

    // TeacherJury
    DateNotScheduled: 'Date non planifiée',
    NoActiveFormula: "Aucune formule d'évaluation active trouvée.",

    // TeacherRequests
    TeacherReqSubtitle: "Gérez vos demandes d'encadrement et validations de projets.",
    SupervFeedbackDefault: "Projet refusé. Veuillez consulter l'encadreur.",
    SubmittedOn: 'Soumis le',
    GitHubRepo_label: 'Dépôt GitHub :',
    NotProvided: 'Non renseigné',
    IrreversibleAction: 'Action irréversible',
    ImportantAction: 'Action importante',
    AcceptSupervBody: "Vous êtes sur le point d'accepter cette demande d'encadrement. Cette action ne peut pas être annulée. Voulez-vous continuer ?",
    FinalApproveWarningInfo: "⚠️ Attention : Approuver une soumission finale valide le projet pour la soutenance. La création de tâches sera désactivée pour ce groupe. Les réunions restent accessibles.",
    FinalApproveBody: "Approuver cette soumission finale valide le projet pour la soutenance. La création de tâches sera désactivée pour ce groupe. Cette action est définitive.",
    RejectFeedbackNote: "Précisez la raison du refus. Le groupe pourra relire ce feedback et soumettre à nouveau.",
    FeedbackPlaceholder2: "Ex : Le rapport final est incomplet, merci de revoir la section méthodologie...",
    Members_label: 'Membres',

    // Student Groupe
    GithubRepoNotFound: 'Dépôt introuvable ou privé',
    GithubConnError: 'Erreur de connexion à GitHub',
    SupervInitialMsg: "Demande d'encadrement initiale lors de la création du groupe.",
    ChooseRoleFirst: 'Veuillez choisir un rôle.',
    ConfirmSupervReqTitle: '⚠️ Confirmation de la demande',
    ConfirmSupervMsg: "Vous allez envoyer une demande d'encadrement à",
    Rejected_label: 'Refusé',
    GroupLockedTitle: 'Groupe verrouillé',
    GroupLockedDesc: "La composition de ce groupe est figée. Pour toute modification, contactez l'administration.",
    IncompleteGroupTitle: 'Équipe incomplète',
    ReqRejectedFull: "a refusé votre demande. Vous devez solliciter un autre enseignant.",
    ReqPendingFull: "Votre demande est en cours de révision par",
    NoSupervisorWarning: "Votre groupe n'a pas encore d'encadreur. Recherchez un enseignant disponible.",
    MeetingNeedsSupervWarn: "⚠️ Vous ne pourrez pas planifier de réunions tant que vous n'aurez pas d'encadreur.",
    SubmissionApprovedMsg: "✨ Votre projet a été officiellement approuvé pour la soutenance !",
    SubmissionPendingMsg: "⏳ Projet soumis à l'encadreur. En attente de validation finale...",
    SubmissionRejectedMsg: "❌ Votre soumission a été refusée. Lisez le feedback ci-dessous et soumettez à nouveau.",
    DeliverableRequired: 'Vous devez déposer au moins un document avant de soumettre.',
    SupervFeedbackLabel: "📢 Feedback de l'encadreur :",
    SelectDocs: 'Sélectionner documents',

    // Student Taches
    TaskTitleRequired: 'Le titre de la tâche est obligatoire.',
    DeadlineInPast: 'La date limite ne peut pas être dans le passé.',
    AssignTaskMember: 'Veuillez assigner la tâche à au moins un membre.',
    JoinGroupFirst_Tasks: "Vous devez rejoindre ou créer un groupe avant de pouvoir gérer des tâches.",
    Task_label: 'Tâche :',
    CurrentBadge: '✓ Actuel',

    // Resources
    AllAuthors: 'Tous les auteurs',
    ResourcesSubtitle: 'Fichiers et liens partagés pour toute la plateforme',
    CategoryOptional: 'Catégorie (optionnel, ex: Tutoriel, Modèle…)',
    SelectFile: 'Sélectionner un fichier',
    NoResourcesFilter: 'Aucune ressource ne correspond à vos filtres.',
    NoResourcesEmpty: "Aucune ressource partagée pour l'instant.",
    HiddenBadge: 'Masqué',
    DownloadBtn: 'Télécharger',

    // AssignStudentModal
    DataLoadError: 'Erreur lors du chargement des données',
    NoUnassignedStudents: 'Aucun étudiant non assigné',
    AllGroupsFull: "Tous les groupes sont complets (6 membres max). L'étudiant doit créer son propre groupe.",
    SelectGroupPlaceholder: '-- Sélectionner un groupe --',

    // ConfirmModal defaults
    DefaultConfirmMsg: 'Êtes-vous sûr de vouloir continuer ?',
    DefaultConfirmPlaceholder: 'Saisissez votre réponse...',

    // Grade mentions
    MentionTresBien: 'Très Bien',
    MentionBien: 'Bien',
    MentionAssezBien: 'Assez Bien',
    MentionPassable: 'Passable',

    // AdminArchive
    ProjectHiddenTooltip: 'Projet masqué — cliquer pour rendre public',
    ProjectPublicTooltip: 'Projet public — cliquer pour masquer',
    ProjectSummaryPlaceholder: 'Résumé du projet...',

    // AdminGroupes
    JuryModificationDisabled: 'Projet noté — modification désactivée',
    EditJuryDefense: 'Modifier jury & soutenance',
    AssignJuryDefense: 'Assigner jury & soutenance',

    // Chart names
    AvgGradeGiven: 'Moyenne donnée',
    NewProjects: 'Nouveaux Projets',
    AverageLabel: 'Moyenne',

    // AdminGroupes extras
    SelectPlaceholder: '— Sélectionner —',
    UngradedForLevel: 'Aucun projet noté pour ce niveau',
    UngradedWarn: 'ne peuvent pas être archivés tant qu\'ils n\'ont pas reçu une note finale',
    UnnotedBadge: 'Non noté',

    // AdminPages Analytics
    ActiveStudents_label: 'Étudiants Actifs',
    InactiveStudents_label: 'Étudiants Inactifs',
    ActiveStudentsChart: 'Actifs',
    InactiveStudentsChart: 'Inactifs',

    // AdminPages advance year confirm
    AdvanceYearConfirmPre: 'Clôturer',
    AdvanceYearConfirmPost: 'et archiver tous les projets actifs ?',

    // Users Import
    LevelDesc1: 'Nouveaux',
    LevelDesc2: '2ème année',
    LevelDesc3: '3ème année',
    LevelDesc4: '4ème année',
    LevelDesc5: '5ème année',
    ImportWarnPreLevel: 'Les étudiants présents dans ce fichier auront leur niveau mis à jour en',
    ImportWarnGrads: 'Les étudiants de l\'année précédente absents de ce fichier seront considérés comme diplômés.',
    ImportWarnTransfers: 'Les nouveaux CIDs seront créés et marqués comme transférés — vérifiez leur année de promotion après l\'import.',
    NewSg: 'nouveau',
    NewPl: 'nouveaux',
    PromotedSg: 'promu',
    PromotedPl: 'promus',
    TransferredSg: 'transféré',
    TransferredPl: 'transférés',
    OrphanSg: 'orphelin',
    OrphanPl: 'orphelins',
    ResultErrorSg: 'erreur',
    ResultErrorPl: 'erreurs',
    OrphansFoundDetail: 'CIDs introuvables (à créer manuellement)',
    TransfersCreatedDetail: 'transféré(s) créé(s) — vérifiez leur année de promotion',
    ImportConfirmBody: 'Vous allez importer',
    ImportConfirmBodyAs: 'comme liste des étudiants',
    ImportConfirmBodyYear: 'de l\'année',
    ImportConfirmBodySuffix: 'Confirmer ?',
    Name_col: 'Nom',
    Password_col: 'Mot de passe',
    ClickToChange: 'Cliquez pour changer',

    // TeacherJury
    JuryPageDisabled: "La page jury est actuellement désactivée par l'administrateur.",

    // Student Reunions
    MeetingRequest: 'Demande de réunion envoyée',
    MustJoinGroup: 'Vous devez rejoindre ou créer un groupe avant de pouvoir planifier des réunions.',
    NoSupervisorMeetings: 'Aucun encadreur assigné',
    NoSupervisorMeetingsDesc: 'Vous ne pouvez pas planifier de réunions tant que votre groupe n\'a pas d\'encadreur approuvé.',
    GoToGroupPage: 'Aller sur la page Groupe',
    UpcomingSection: 'À venir',
    HistorySection: 'Historique',
    NoUpcomingMeetings: 'Aucune réunion planifiée',
    NewMeeting: 'Nouvelle réunion',
    ScheduledByTeacher: 'Planifiée par l\'encadreur',
    ViewAttendance: 'Voir les présences',
    MeetingType_Pres: 'Présentielle',
    DateRequired: 'Veuillez choisir une date.',
    DatePastError: 'La date ne peut pas être dans le passé.',
    DateTooFarError: 'La date est trop éloignée. Veuillez choisir une date dans l\'année académique.',
    TimeRequired: 'Veuillez choisir une heure.',
    TitleRequired: 'Veuillez saisir un objet pour la réunion.',
    MeetingStatusPending2: 'En attente',
    MeetingStatusAccepted: 'Acceptée',
    MeetingStatusRejected2: 'Refusée',
    MeetingStatusCancelled2: 'Annulée',
    CalendarDays: 'Lun,Mar,Mer,Jeu,Ven,Sam,Dim',
  },
  en: {
    // Nav / Sidebar
    Dashboard: 'Dashboard',
    Projects: 'Projects',
    Archive: 'Archive',
    Groups: 'Groups',
    Students: 'Students',
    Teachers: 'Teachers',
    Admin: 'Administration',
    Users: 'Users',
    Supervision: 'Supervision',
    Juries: 'Juries',
    MyProject: 'My Project',
    Tasks: 'Tasks',
    Meetings: 'Meetings',
    Profile: 'Profile',
    Evaluations: 'Evaluations',
    Year: 'Study Year',
    Settings: 'Settings',
    Logout: 'Logout',
    Requests: 'Requests',

    // Common phrases
    Search: 'Search...',
    Save: 'Save',
    Cancel: 'Cancel',
    Delete: 'Delete',
    Edit: 'Edit',
    Submit: 'Submit',
    Approve: 'Approve',
    Reject: 'Reject',
    Status: 'Status',
    Date: 'Date',
    Loading: 'Loading...',
    Error: 'Error',
    Success: 'Success',
    Confirm: 'Confirm',

    // Home Page
    HomeTitle: 'Manage your academic projects with',
    HomeSubtitle: 'The all-in-one platform for ESI students, supervisors, and administration. Collaborate, code, and succeed.',
    HomeBadge: '🎓 University Platform',
    GetStarted: 'Get Started',
    LearnMore: 'Learn More',
    StatsActiveStudents: 'Active Students',
    StatsProjects: 'Managed Projects',
    StatsTeachers: 'Supervisors',
    StatsUptime: 'System Uptime',
    FeaturesTitle: 'Everything you need',
    FeaturesSubtitle: 'A complete suite of tools to support every stage of your graduation project.',
    ReadyToStart: 'Ready to start?',
    ReadyToStartSub: 'Log in with your ESI account to access your workspace.',
    LoginBtn: 'Log In',
    FooterText: 'ESI-GIT — Higher School of Computer Science. All rights reserved.',
    Feature1Title: 'Git Management', Feature1Desc: 'Native Git repository integration for every academic project.',
    Feature2Title: 'Teamwork', Feature2Desc: 'Easily create and manage your project groups.',
    Feature3Title: 'Scheduling', Feature3Desc: 'Organize meetings with your supervisor seamlessly.',
    Feature4Title: 'Kanban Board', Feature4Desc: 'Track tasks in real time with an intuitive Kanban board.',
    Feature5Title: 'Tracking & Grading', Feature5Desc: 'Transparent grading and structured feedback on each deliverable.',
    Feature6Title: 'Secure Access', Feature6Desc: 'Distinct roles for students, supervisors, and administration.',

    // Extended Dashboard & Groups
    DashboardGreeting: 'Hello',
    TasksCompleted: 'Tasks completed',
    PlannedMeetings: 'Planned meetings',
    OverallProgress: 'Overall progress',
    TeacherTasks: 'Supervisor tasks',
    ProjectProgress: 'Project progress',
    InProgress: 'In progress',
    NotStarted: 'Not started yet',
    RecentActivity: 'Recent activity',
    UpcomingDeadlines: 'Upcoming deadlines',
    MyGroup: 'My group',
    NoActivity: 'No activity for now',
    NoGroupDetails: 'You do not have a group yet',
    CreateJoinGroup: 'Create / join a group',
    TaskOrigin: 'Task origin',
    TaskStatus: 'Task status',
    Deliverables: 'Deliverables',
    GroupTitle: 'Group',
    GroupSubtitle: 'Create or join a project group',
    CreateGroup: 'Create',
    JoinGroup: 'Join',
    MyGroupTitle: 'My Group',
    MyGroupSub: 'Members, roles and repository of your team',
    CurrentGroup: 'Current group',
    InviteCode: 'Invitation code',
    Copy: 'Copy',
    Copied: 'Copied !',
    GithubRepo: 'GitHub Repository',
    Load: 'Load',
    Open: 'Open',
    ChooseFile: 'Choose file',
    JuryAssigned: 'Jury Assigned',
    'JuryRoles.president': 'President',
    'JuryRoles.examiner': 'Examiner',
    'JuryRoles.supervisor': 'Supervisor',
    'JuryRoles.member': 'Member',
    AssignJury: 'Assign Jury',
    EditJury: 'Edit Jury',
    NoJuryAssigned: 'No jury assigned',
    WaitSupervisorValidation: 'Waiting for supervisor validation',
    ValidationRequestSub: 'Select the jury members for this project.',
    NoFile: 'No PDF document uploaded',
    ProjectValidation: 'Project validation',
    SubmitProjectToSup: 'Submit your project to your supervisor for final validation.',
    TeamMembers: 'Team',
    ChangeRole: 'Change role',
    LeaveGroup: 'Leave group',

    // Teacher
    MyGroups: 'My groups',
    GroupsSupervision: 'Groups under your supervision',
    NoGroupYet: 'No group at the moment.',
    ClickGroupDetails: 'Click on a group to see details',
    AllGroups: 'All groups',
    ValidationRequest: 'Validation request',
    AssignTask: 'Assign a task',
    ScheduleMeeting: 'Schedule a meeting',

    // Tasks Page
    TaskManagement: 'Task Management',
    TasksCompleted_Subtitle: 'tasks completed',
    NewTask: 'New Task',
    GlobalProgress: 'Global Progress',
    DropHere: 'Drop here',
    CreateTask: 'Create a Task',
    TaskTitle: 'Task Title',
    Description: 'Description',
    Priority: 'Priority',
    Column: 'Column',
    Tag: 'Tag / Category',
    AssignMembers: 'Assign Members',
    High: 'High',
    Medium: 'Medium',
    Low: 'Low',
    Todo: 'To Do',
    Hide: 'Hide',
    Actions: 'Actions',
    Done: 'Done',
    InProgress_Short: 'In Progress',

    // Teacher Groups
    SupervisionRequests: 'Supervision Requests',
    SupervisedGroups: 'Supervised Groups',
    NoPendingRequests: 'No pending supervision requests.',
    NoSupervisedGroups: 'You have no supervised groups at the moment.',
    ApproveRequest: 'Accept',
    NewValidationRequest: 'New Validation Request',
    NewValidationRequestSub: 'This group has submitted their project for final validation.',
    LastCommits: 'Last Commits',
    Members: 'Group Members',
    AssignTo: 'Assign to',
    IfNoneSelected: 'If none selected → assigned to all members',
    MeetingAutoAccepted: 'Meetings scheduled by the supervisor are automatically accepted.',

    // Teacher Dashboard
    TeacherDashboard: 'Supervisor Dashboard',
    RealDataAnalytics: 'Analytics calculated from real data',
    SupervisedGroups_Stat: 'Supervised Groups',
    ActiveGroups_Stat: 'Active Groups',
    AvgProgress_Stat: 'Average Progress',
    CompletionRate_Stat: 'Completion Rate',
    PendingMeetings_Stat: 'Pending Meetings',
    PendingEvals_Stat: 'Pending Evaluations',
    ProgressByGroup: 'Progress by Group',
    TaskState: 'Task State',
    TasksByPriority: 'Tasks by Priority',
    NoGroups: 'No Groups',
    FinalValidationRequests: 'Final Validation Requests (Completed Projects)',
    ProjectSubmittedFinal: 'Project submitted for end-of-year validation',
    ValidateProject: 'Validate Project',
    SendWithCorrections: 'Send with Corrections',

    // Jury
    DefenseJury: 'Defense Jury',
    JuryParticipation: 'Defenses in which you participate as a jury member',
    Assigned: 'Assigned',
    ToEvaluate: 'To Evaluate',
    Evaluated: 'Evaluated',
    Scheduled: 'Scheduled',
    Evaluate: 'Evaluate',
    DefenseEvaluation: 'Jury Evaluation',
    FinalGradeCalculated: 'Final grade calculated',
    EvaluationComments: 'Evaluation comments',

    // Archive
    ArchiveTitle: 'Project Archive',
    ArchiveSubtitle: 'Final year projects from previous years',
    AvgGrade: 'Average',
    Mentions: 'Mentions',
    Years: 'Years',
    FilterBy: 'Filter By',
    CurrentSupervisor: 'Current Supervisor',
    ManageSupervision: 'Manage your project supervision',
    RequestNewSupervisor: 'Request a new supervisor',
    NoSupervisorAssigned: 'No supervisor assigned yet.',
    PendingRequest: 'Pending Request',
    PendingRequestMsg: 'You already have a pending request. You must wait for a response before sending another one.',
    RequestHistory: 'Request History',
    NoRequestsSent: 'No requests sent.',
    Wait: 'Wait',
    Rejected: 'Rejected',
    Accepted: 'Accepted',
    RequestSent: 'Request sent!',
    SendRequest: 'Send Request',
    ConfirmSend: 'Confirm Sending',
    AccompanyingMessage: 'Accompanying Message (Optional)',
    ExplainSubject: 'Briefly explain your project subject...',
    SearchByTeacherName: 'Search by name or specialty...',
    OfficialSupervisor: 'Official project supervisor',
    YearFilter: 'Year',
    Supervisor: 'Supervisor',
    All: 'All',
    Validated: 'Validated',

    // Admin
    AdminDashboard: 'Admin Dashboard',
    RealTimeAnalytics: 'Real-time analytics — data calculated from base',
    TotalStudents_Stat: 'Total students',
    Teachers_Stat: 'Teachers',
    ArchivedProjects_Stat: 'Archived Projects',
    AvgProgressBySupervisor: 'Average progress by supervisor',
    WeightedAvgProgress: 'Weighted average progress',
    UserDistribution: 'User distribution',
    Admins: 'Admins',
    GroupsPerSpecialty: 'Groups per specialty',
    ProjectState: 'Project state',
    TotalTasks_Stat: 'Total tasks',
    AssignedBySupervisor: 'Assigned by supervisor',
    CreatedByStudents: 'Created by students',
    OverallAverage: 'Overall average',
    Mentions_Stat: 'Mentions',
    NoGroupAssigned: 'No group assigned yet',

    // User Management
    UserManagement: 'Users',
    AddUser: 'Add User',
    EditUser: 'Edit User',
    DeleteUser: 'Delete User',
    UserDetail: 'User Detail',
    Identity: 'Identity',
    StudentInfo: 'Student Information',
    TeacherInfo: 'Teacher Information',
    AssignStudent: 'Assign Student',
    AvailableForSupervision: 'Available for supervision',
    Department: 'Department',
    TeachingSpecialty: 'Teaching Specialty',
    Displaying: 'Showing',
    To: 'to',
    Of: 'of',
    ConfirmDeleteUser: 'Are you sure you want to delete this user? This action is irreversible.',

    // Group Management (Admin)
    GroupDetail: 'Group Detail',
    TotalGroups_Stat: 'Total groups',
    Active_Stat: 'Active',
    NonApproved_Stat: 'Non approved',
    StudentsWithoutGroup: 'Students without group',
    CreateGroupTitle: 'Create New Group',
    ProjectTitle: 'Project Title',
    GroupCode: 'Group Code',
    GroupManagement: 'Group management',
    AllStudentsInGroup: 'All students have a group',

    // Profil
    ProfileTitle: 'Profile',
    ProfileSubtitle: 'Your personal information',
    PersonalInfo: 'Personal Information',
    FullName: 'Full Name',
    Email: 'Email Address',
    Specialty: 'Specialty',
    Promotion: 'Promotion',
    L1: '1st Year (L1)',
    L2: '2nd Year (L2)',
    L3: '3rd Year (L3)',
    M1: 'Master 1 (M1)',
    M2: 'Master 2 (M2)',
    AdminLock: '🔒 Profile information is managed by administration. Contact your manager for any modification.',
    SwitchToTeacher: 'Switch to Teacher Mode',
    SwitchToAdmin: 'Switch to Admin Mode',
    BackToTop: 'Scroll to top',
    Notifications: 'Notifications',
    ActiveProjects: 'Active Projects',
    SubmissionsThisMonth: 'Submissions this month',
    AvgCompletionRate: 'Average Completion Rate',
    HideArchiveStudent: 'Hide Archive (Students)',
    HideArchiveStudent_Desc: 'Students will no longer be able to see the project archive.',
    HideJuryTeacher: 'Hide Juries (Teachers)',
    HideJuryTeacher_Desc: 'Teachers will no longer be able to access jury evaluations.',

    // Missing keys added
    GroupName: 'Group Name',
    ProjectTheme: 'Project Theme',
    Role: 'Role',
    StatusUpdated: 'Status updated',
    FirstName: 'First Name',
    LastName: 'Last Name',
    AcademicYear: 'Academic Year',
    Level: 'Level',
    Groups_Stat: 'Groups',
    NoData: 'No data available',
    ProjectType: 'Project Type',
    ProjectDescription: 'Project Description',
    CreateProject: 'Create a project',
    SupervisorAvailability: 'Availability',
    Blocked: 'Blocked',
    Block: 'Block',
    Unblock: 'Unblock',
    CyclePrepa: 'Preparatory Cycle',
    CycleSuperieur: 'Superior Cycle',
    Department: 'Department',
    PasswordChanged: 'Password changed successfully',
    PasswordError: 'Error changing password',
    OldPassword: 'Old password',
    NewPassword: 'New password',
    ConfirmPassword: 'Confirm password',
    ChangePassword: 'Change Password',
    BlockUser: 'Block',
    UnblockUser: 'Unblock',
    ResetPassword: 'Reset Password',

    // Admin Analytics & Settings
    PlatformAnalytics: 'Platform Analytics',
    ConsolidatedData: 'Consolidated Data',
    ExportCSV: 'Export Report (CSV)',
    SuccessRate: 'Success Rate',
    StudentsAtRisk: 'Students at Risk',
    GradeTrends: 'Grade Trends',
    StudentActivity: 'Student Activity',
    NotationPatterns: 'Grading Patterns (Teachers)',
    UsageTrends: 'Usage Trends',
    AcademicYears: 'Academic Years',
    ActiveYear: 'Active Year',
    ActivePromos: 'Active Promotions',
    AddPromo: 'Add Promotion',
    ChangeYearWarning: '⚠️ Changing the active year will automatically archive all current projects.',
    SpecialtiesThemes: 'Specialties & Themes',
    GradingFormula: 'Grading Formula',
    FormulaList: 'Existing Formulas',
    ActiveStatus: 'ACTIVE',
    VisibilityAccess: 'Visibility & Access',
    ShowArchiveStudents: 'Show archive to students',
    ShowArchiveStudents_Desc: 'Allows students to view previous projects.',
    NewFormula: 'New Formula',
    Expression: 'Expression',

    // Admin Users Extra
    NewPasswordOptional: 'New Password (optional)',
    LeaveEmptyNoChange: 'Leave empty for no change',
    Choose: 'Choose',
    ImportUsers: 'Import Users',
    StaffMembers: 'Teachers / Staff',
    AccountsCreated: 'Accounts created successfully',
    StaffNote: 'Note: A Staff user can be both Teacher and Admin.',
    DragDropFile: 'Drag your file here',
    Browse: 'browse',
    ImportInProgress: 'Import in progress...',
    Imported: 'user(s) imported!',
    RowsIgnored: 'row(s) ignored',
    Summary: 'Summary',
    StudentList: 'Student List',
    Grade: 'Grade',

    // Student Dashboard (new)
    TaskProgress: 'Task Progress',
    TasksDone: 'Tasks done',
    NoOverdue: 'No overdue',
    OverdueTasks: 'overdue task(s)',
    FinalSubmission: 'Final Submission',
    AttendanceRate: 'Attendance Rate',
    Meetings_label: 'meetings',
    FinalGrade: 'Final Grade',
    NextMeeting: 'Next Meeting',

    // Teacher Dashboard (new)
    TasksDoneByGroup: 'Tasks done by group',
    PendingRequestsStat: 'Pending Requests',
    GroupsToWatch: 'Groups to watch',
    AllGroupsOnTrack: 'All groups are on track',
    Tasks_label: 'Tasks',
    Health_label: 'Health',
    Health_OnTrack: '🟢 OK',
    Health_Watch: '🟡 Watch',
    Health_AtRisk: '🔴 At risk',

    // Admin Dashboard (new)
    NoGroup_Stat: 'Without group',
    PendingApprovals_Stat: 'Pending Approvals',
    DefenseReadiness: 'Defense Readiness',
    DefenseSubtitle: 'Global funnel · active projects',
    ActiveProjects_label: 'Active projects',
    JuriesAssigned_label: 'Juries assigned',
    DefensesScheduled_label: 'Defenses scheduled',
    Graded_label: 'Graded',
    ReadyToArchive_label: 'Ready to archive',
    ByLevel: 'By level',
    Graded_count: 'graded',

    // Admin Analytics (new)
    FailRate: 'Fail Rate',

    // Admin Dashboard labels
    Pending_label: 'Pending',
    Approved_label: 'Approved',
    Archived_label: 'Archived',

    // TeacherJury
    DateNotScheduled: 'Date not scheduled',
    NoActiveFormula: 'No active evaluation formula found.',

    // TeacherRequests
    TeacherReqSubtitle: 'Manage your supervision requests and project validations.',
    SupervFeedbackDefault: 'Project rejected. Please contact your supervisor.',
    SubmittedOn: 'Submitted on',
    GitHubRepo_label: 'GitHub Repo:',
    NotProvided: 'Not provided',
    IrreversibleAction: 'Irreversible action',
    ImportantAction: 'Important action',
    AcceptSupervBody: "You are about to accept this supervision request. This action cannot be undone. Do you want to continue?",
    FinalApproveWarningInfo: "⚠️ Warning: Approving a final submission validates the project for defense. Task creation will be disabled for this group. Meetings remain accessible.",
    FinalApproveBody: "Approving this final submission validates the project for defense. Task creation will be disabled for this group. This action is final.",
    RejectFeedbackNote: "Specify the reason for rejection. The group can re-read this feedback and resubmit.",
    FeedbackPlaceholder2: "E.g.: The final report is incomplete, please revise the methodology section...",
    Members_label: 'Members',

    // Student Groupe
    GithubRepoNotFound: 'Repository not found or private',
    GithubConnError: 'GitHub connection error',
    SupervInitialMsg: 'Initial supervision request upon group creation.',
    ChooseRoleFirst: 'Please choose a role.',
    ConfirmSupervReqTitle: '⚠️ Confirm Request',
    ConfirmSupervMsg: 'You are about to send a supervision request to',
    Rejected_label: 'Rejected',
    GroupLockedTitle: 'Group locked',
    GroupLockedDesc: "This group's composition is locked. For any change, contact administration.",
    IncompleteGroupTitle: 'Incomplete team',
    ReqRejectedFull: 'rejected your request. You must contact another teacher.',
    ReqPendingFull: 'Your request is being reviewed by',
    NoSupervisorWarning: "Your group doesn't have a supervisor yet. Search for an available teacher.",
    MeetingNeedsSupervWarn: "⚠️ You won't be able to schedule meetings until you have a supervisor.",
    SubmissionApprovedMsg: '✨ Your project has been officially approved for defense!',
    SubmissionPendingMsg: '⏳ Project submitted to supervisor. Waiting for final validation...',
    SubmissionRejectedMsg: '❌ Your submission was rejected. Read the feedback below and resubmit.',
    DeliverableRequired: 'You must upload at least one document before submitting.',
    SupervFeedbackLabel: '📢 Supervisor Feedback:',
    SelectDocs: 'Select files',

    // Student Taches
    TaskTitleRequired: 'Task title is required.',
    DeadlineInPast: 'Deadline cannot be in the past.',
    AssignTaskMember: 'Please assign the task to at least one member.',
    JoinGroupFirst_Tasks: 'You must join or create a group before managing tasks.',
    Task_label: 'Task:',
    CurrentBadge: '✓ Current',

    // Resources
    AllAuthors: 'All authors',
    ResourcesSubtitle: 'Files and links shared across the platform',
    CategoryOptional: 'Category (optional, e.g.: Tutorial, Template…)',
    SelectFile: 'Select a file',
    NoResourcesFilter: 'No resources match your filters.',
    NoResourcesEmpty: 'No shared resources yet.',
    HiddenBadge: 'Hidden',
    DownloadBtn: 'Download',

    // AssignStudentModal
    DataLoadError: 'Error loading data',
    NoUnassignedStudents: 'No unassigned students',
    AllGroupsFull: 'All groups are full (6 members max). The student must create their own group.',
    SelectGroupPlaceholder: '-- Select a group --',

    // ConfirmModal defaults
    DefaultConfirmMsg: 'Are you sure you want to continue?',
    DefaultConfirmPlaceholder: 'Enter your response...',

    // Grade mentions
    MentionTresBien: 'Very Good',
    MentionBien: 'Good',
    MentionAssezBien: 'Fairly Good',
    MentionPassable: 'Pass',

    // AdminArchive
    ProjectHiddenTooltip: 'Hidden project — click to make public',
    ProjectPublicTooltip: 'Public project — click to hide',
    ProjectSummaryPlaceholder: 'Project summary...',

    // AdminGroupes
    JuryModificationDisabled: 'Graded project — editing disabled',
    EditJuryDefense: 'Edit jury & defense',
    AssignJuryDefense: 'Assign jury & defense',

    // Chart names
    AvgGradeGiven: 'Average given',
    NewProjects: 'New Projects',
    AverageLabel: 'Average',

    // AdminGroupes extras
    SelectPlaceholder: '— Select —',
    UngradedForLevel: 'No graded projects for this level',
    UngradedWarn: 'cannot be archived until they receive a final grade',
    UnnotedBadge: 'Ungraded',

    // AdminPages Analytics
    ActiveStudents_label: 'Active Students',
    InactiveStudents_label: 'Inactive Students',
    ActiveStudentsChart: 'Active',
    InactiveStudentsChart: 'Inactive',

    // AdminPages advance year confirm
    AdvanceYearConfirmPre: 'Close',
    AdvanceYearConfirmPost: 'and archive all active projects?',

    // Users Import
    LevelDesc1: 'New',
    LevelDesc2: '2nd year',
    LevelDesc3: '3rd year',
    LevelDesc4: '4th year',
    LevelDesc5: '5th year',
    ImportWarnPreLevel: 'Students in this file will have their level updated to',
    ImportWarnGrads: 'Students from the previous year absent from this file will be considered graduates.',
    ImportWarnTransfers: 'New CIDs will be created and marked as transferred — verify their graduation year after import.',
    NewSg: 'new',
    NewPl: 'new',
    PromotedSg: 'promoted',
    PromotedPl: 'promoted',
    TransferredSg: 'transferred',
    TransferredPl: 'transferred',
    OrphanSg: 'orphan',
    OrphanPl: 'orphans',
    ResultErrorSg: 'error',
    ResultErrorPl: 'errors',
    OrphansFoundDetail: 'CIDs not found (to create manually)',
    TransfersCreatedDetail: 'transferred (created) — check their year of promotion',
    ImportConfirmBody: 'You are about to import',
    ImportConfirmBodyAs: 'as the student list for',
    ImportConfirmBodyYear: 'for academic year',
    ImportConfirmBodySuffix: 'Confirm?',
    Name_col: 'Name',
    Password_col: 'Password',
    ClickToChange: 'Click to change',
    Specialite: 'Specialty',

    // Student Reunions
    MeetingRequest: 'Meeting request sent',
    MustJoinGroup: 'You must join or create a group before scheduling meetings.',
    NoSupervisorMeetings: 'No supervisor assigned',
    NoSupervisorMeetingsDesc: 'You cannot schedule meetings until your group has an approved supervisor.',
    GoToGroupPage: 'Go to Group Page',
    UpcomingSection: 'Upcoming',
    HistorySection: 'History',
    NoUpcomingMeetings: 'No upcoming meetings',
    NewMeeting: 'New meeting',
    ScheduledByTeacher: 'Scheduled by supervisor',
    ViewAttendance: 'View attendance',
    MeetingType_Pres: 'In person',
    DateRequired: 'Please choose a date.',
    DatePastError: 'Date cannot be in the past.',
    DateTooFarError: 'Date is too far ahead. Please choose a date within the academic year.',
    TimeRequired: 'Please choose a time.',
    TitleRequired: 'Please enter a subject for the meeting.',
    MeetingStatusPending2: 'Pending',
    MeetingStatusAccepted: 'Accepted',
    MeetingStatusRejected2: 'Rejected',
    MeetingStatusCancelled2: 'Cancelled',
    CalendarDays: 'Mon,Tue,Wed,Thu,Fri,Sat,Sun',

    // Teacher Meetings
    PendingMeetings: 'Pending',
    UpcomingMeetings: 'Upcoming',
    PastCancelledMeetings: 'Past / Cancelled',
    AllGroups2: 'All groups',
    NoMeetings: 'No meetings yet',
    ApproveMeeting: '✓ Approve',
    RejectMeeting: '✕ Reject',
    CancelMeeting: 'Cancel',
    Attendances: '📋 Attendance',
    CancellationReason: 'Cancellation reason:',
    AttendancesTitle: 'Attendance',
    CheckPresentMembers: 'Check present members',
    NoMembersFound: 'No members found',
    SavingAttendance: 'Saving…',
    SaveAttendance: 'Save',
    CancelConfirmTitle: 'Confirm Cancellation',
    CancelReasonPlaceholder: 'Cancellation reason (optional)...',
    AttendanceSaved: 'Attendance saved',
    AttendanceSaveError: 'Error saving attendance',
    CancelError: 'Error cancelling meeting',
    LoadAttendanceError: 'Could not load attendance',
    MeetingStatusPending: 'Pending',
    MeetingStatusApproved: 'Scheduled',
    MeetingStatusRejected: 'Rejected',
    MeetingStatusCancelled: 'Cancelled',

    // Teacher Groups
    Encadreur: 'Supervisor',
    NoRepo: 'No repository provided by the group.',
    DownloadAllDocs: '⬇ Download all',
    NotAvailable: 'Unavailable',
    Open2: 'Open',
    GroupMembers: 'member(s)',
    NoDocuments: 'No documents attached.',
    ProjectDocs: 'Project Documents',
    ProjectApproved: 'Project approved',
    Deadline: 'Deadline',

    // TeacherJury
    JuryPageDisabled: 'Jury access is currently disabled by the admin.',

    // Admin Settings — PanelYears
    CloseYearAdvance: 'Close Year & Advance',
    CloseYearDesc: 'Archives all active projects and automatically advances to the next year. This action is irreversible.',
    ChangeYearTitle: 'Change year?',
    ChangeYearMsg: 'Changing the academic year will ARCHIVE all current projects. This action is irreversible.',
    ChangeAndArchive: 'Change & Archive',
    PlatformConfig: 'Platform Configuration',
    NeedHelp: 'Need help?',
    HelpDesc: 'Consult the documentation to configure advanced platform settings.',

    // Admin Settings — PanelCategories
    SpecialtyAdded: 'Specialty added',
    SpecialtyDeleted: 'Deleted',
    AbbrevPlaceholder: 'Abbreviation (e.g. ISI)',
    FullNamePlaceholder: 'Full name (e.g. Inf. Systems Engineering)',

    // Admin Settings — PanelVisibility
    DeliverableVisible: 'Deliverables visible (students)',
    DeliverableVisible_Desc: 'Students can view deliverables from archived projects',
    JuryPageVisible: 'Enable jury page (teachers)',
    JuryPageVisible_Desc: 'Teachers can access the jury evaluation page',
    SystemEmail: 'System email',
    SystemEmailDesc: 'Used as the sending address for credentials, password resets, and system notifications',
    GroupLockDeadline: '🔒 Group formation deadline',
    GroupLockDeadlineDesc: 'After this date, all groups will be automatically locked (no more join / leave / kick). Students without a group will see an access-closed message. Leave empty to disable automatic locking.',
    LockActiveFrom: '⚠️ Lock active from',

    // Admin Settings — PanelGradingFormula
    Name: 'Name',
    Optional: 'optional',
    Components: 'Grade components',
    Coefficient: 'Coef.',
    Add: 'Add',
    Reset: 'Reset',
    Active: 'ACTIVE',
    Activate: 'Activate',
    SavedFormulas: 'Saved formulas',
    NoFormulas: 'No formulas defined',
    Saved: 'Saved',
    fieldsRequired: 'Required fields',

    // Admin Groupes — JuryScheduleModal
    JurySelected: 'selected',
    SupervisorMustBeInJury: '⚠️ The supervisor must be part of the jury.',
    ExactlyOnePresident: '⚠️ Exactly 1 president required.',
    DefenseOptional: 'Defense (optional — can be completed later)',
    Time: 'Time',
    Room: 'Room',
    PastDateError: 'Date cannot be in the past.',
    JuryComplete: '✅ Jury complete',
    DefenseScheduled: 'Defense scheduled',
    JuryMembersCount: 'jury members',

    // Admin Groupes — GroupDetailModal
    Graded: 'Graded',
    DefenseTitle: 'Defense',
    NotScheduled: 'Not scheduled',
    Deliverables_title: 'Deliverables',
    NoDeliverable: 'No deliverable submitted.',
    DownloadAll: '⬇ Download all',

    // Admin Groupes — EditGroupModal
    ModifyGroup: 'Edit',
    MembersCount: 'Members',
    GroupLeader: 'Leader',
    RemoveMember: 'Remove',
    AddStudent: 'Add a student',
    NoStudentAvailable: 'No students without a group available for this level.',
    SupervisorSection: 'Supervisor',
    ChangeSupervisor: 'Change supervisor',
    ArchiveGroup: 'Archive',

    // Admin Groupes — CreateGroupModal
    ProjectTypeLabel: 'Project Type *',
    TitleDefaultNote: '📌 The project title will be "temp" by default. The group leader can edit the name and type after creation.',
    LeaveEmptyLater: 'Leave empty for the group to choose later.',
    NoResults: 'No results',
    Approved_Stat: 'Approved',

    // Admin Groupes — ArchiveAllModal
    CloseArchiveProjects: 'Close & archive projects',
    OnlyGradedArchivable: 'Only graded projects can be archived.',
    FilterByLevel: 'Filter by level',
    GradedProjects: 'Graded projects',
    Archivable: 'archivable',
    UngradedProjects: 'Ungraded projects',
    WontBeArchived: 'will not be archived',
    IrreversibleArchive: 'Archiving is irreversible. Archived projects can no longer be modified by students.',
    Continue: 'Continue',
    Selected: 'selected',
    FinalConfirmation: 'Final confirmation',
    ArchiveConfirmMsg: 'You are about to archive these projects — this action is irreversible.',
    TypeToConfirm: 'Type ARCHIVE to confirm:',
    TypeArchive: 'Type ARCHIVE',
    Back: 'Back',
    ArchivingInProgress: 'Archiving in progress…',
    ArchiveNow: 'Archive now',
    SelectAll: 'Select all',
    DeselectAll: 'Deselect all',
    ArchiveAll: 'Archive all',
    AllTags: 'All tags',
    AllLevels: 'All levels',
    AllSupervisors: 'All supervisors',
    ActiveTag: 'Active',
    ApprovedTag: 'Approved',
    GradedTag: 'Graded',
    ReadyForDefense: 'Ready for defense',
    JuryOkDateMissing: '⏳ Jury ✓ — Date missing',
    JuryRequired: '⏳ Jury required',
    GradedScore: 'Graded —',

    // Admin Students
    StudentAssignments: 'Student Assignments',
    StudentAssignmentsSub: 'View and manage student group membership status.',
    WithGroup: 'With Group',
    WithoutGroup: 'Without Group',
    NotAssigned: 'Not assigned',
    Project: 'Project',
    Student: 'Student',
    Previous: 'Previous',
    Next: 'Next',

    // Admin Users
    ImportExcel: 'Import Excel',
    FileLevel: 'FILE LEVEL',
    ConfirmImport: 'Confirm import',
    Grades: 'Grades',
    AlreadyExists: 'Already exists — level updated',
    PasswordSentByEmail: '✉️ Password sent by email',
    ExpectedColumns: '📋 Expected columns:',
    ImportAnotherFile: '↩ Import another file',
    DeleteSelection: 'Delete selection?',
    ConfirmBulkDelete: 'Are you sure you want to permanently delete these users?',
    BulkDeleted: 'users deleted',
    BulkDeleteError: 'Error during bulk deletion',
    Dispo: '🟢 Available',
    Indispo: '🔴 Unavailable',
    Roles: 'Role',
    AllLevels2: 'All levels',
    ID_Matricule: 'ID / Matricule (National ID)',
    YearLabel1: '1st Year (1CPI)',
    YearLabel2: '2nd Year (2CPI)',
    YearLabel3: '3rd Year (1CS / 3CS)',
    YearLabel4: '4th Year (2CS / 4CS)',
    YearLabel5: '5th Year (3CS / 5CS)',

    // Admin Archive
    ArchiveVisibleStudents: '🔓 Archive visible to students',
    ArchivHiddenStudents: '🔒 Archive hidden from students',
    ArchiveVisibilityNote: 'This option enables/disables the Archive tab for all students.',
    AvgGrade_Stat: 'Average',
    Mention: 'Mentions',
    Found: 'found',
    NoDescription: 'No description available.',
    ProjectPublic: 'Public',
    ProjectPrivate: 'Private',
    ProjectVisibility: 'Project visibility',
    ProjectVisibilityDesc: 'Make the project visible (public) or hide it (private).',
    ProjectHidden: 'Project hidden — click to make public',
    ProjectPublicTitle: 'Public project — click to hide',
    DeleteConfirmation: 'This action is irreversible.',
    SearchSupervisor: 'Search supervisor...',
    Technologies: 'TECHNOLOGIES (comma-separated)',

    // Admin Dashboard
    NoUsersYet: 'No users yet.',
    NoGradesYet: 'No grades recorded',
    AvgNotesByTeacher: 'Average grades — Teachers',

    // Admin Notifications
    NotifSend: 'Send Notification',
    NotifSendLabel: 'Send a notification',
    NotifTitle: 'Title',
    NotifMessage: 'Message',
    NotifAudience_all: 'Everyone',
    NotifAudience_students: 'Students',
    NotifAudience_staff: 'Teachers / Staff',
    NotifLevelOptional: 'Level (optional)',
    NotifSpecialtyOptional: 'Specialty (optional)',
    AllSpecialties: 'All specialties',
    NotifHistory: 'Sent notifications',
    NotifNoHistory: 'No notifications sent.',
    Refresh: 'Refresh',
    Sending: 'Sending…',
    SendNotification: 'Send notification',
    NotifTitleRequired: 'Title and message required.',
    NotifSentSuccess: 'Notification sent',
    NotifDeleteFail: 'Deletion failed',
    NotifSendFail: 'Sending failed',
    NotifDeleted: 'Deleted',

    // Admin Profil
    CurrentPassword: 'Current password',
    Departement: 'Department',

    // Admin Analytics
    Available: 'Available',
    Unavailable: 'Unavailable',
    SupervisorAvailability: 'Availability',
  }
};

export function LanguageProvider({ children }) {
  const [lang, setLang] = useState('fr');

  useEffect(() => {
    const saved = localStorage.getItem('appLang');
    if (saved && (saved === 'fr' || saved === 'en')) {
      setLang(saved);
      document.documentElement.lang = saved;
    } else {
      document.documentElement.lang = 'fr';
    }
  }, []);

  const toggleLanguage = () => {
    const nextLang = lang === 'fr' ? 'en' : 'fr';
    setLang(nextLang);
    localStorage.setItem('appLang', nextLang);
    document.documentElement.lang = nextLang;
  };

  const t = (key) => {
    if (!translations[lang]) return key;
    return translations[lang][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ lang, toggleLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  return useContext(LanguageContext);
}
