import { createContext, useContext, useState, useEffect } from 'react';

const LanguageContext = createContext();

export const translations = {
  fr: {
    // Nav / Sidebar
    Dashboard: 'Tableau de bord',
    Projects: 'Projets',
    Archive: 'Archive',
    Groups: 'Groupes',
    Students: 'Étudiants',
    Teachers: 'Enseignants',
    Admin: 'Administration',
    Users: 'Utilisateurs',
    Supervision: 'Encadrement',
    Juries: 'Jurys',
    MyProject: 'Mon Projet',
    Tasks: 'Tâches',
    Meetings: 'Réunions',
    Profile: 'Profil',
    Evaluations: 'Évaluations',
    Year: 'Année d\'étude',
    Settings: 'Paramètres',
    Logout: 'Déconnexion',
    Requests: 'Demandes',

    // Common phrases
    Search: 'Rechercher...',
    Save: 'Enregistrer',
    Cancel: 'Annuler',
    Delete: 'Supprimer',
    Edit: 'Modifier',
    Submit: 'Soumettre',
    Approve: 'Approuver',
    Reject: 'Refuser',
    status: 'Statut',
    Date: 'Date',
    Loading: 'Chargement...',
    Error: 'Erreur',
    Success: 'Succès',
    Confirm: 'Confirmer',

    // Home Page
    HomeTitle: 'Gérez vos projets académiques avec',
    HomeSubtitle: 'La plateforme tout-en-un pour les étudiants, les encadreurs et l\'administration de l\'ESI. Collaborez, codez et réussissez.',
    HomeBadge: '🎓 Plateforme universitaire',
    GetStarted: 'Commencer maintenant',
    LearnMore: 'En savoir plus',
    StatsActiveStudents: 'Étudiants actifs',
    StatsProjects: 'Projets gérés',
    StatsTeachers: 'Encadreurs',
    StatsUptime: 'Disponibilité',
    FeaturesTitle: 'Tout ce dont vous avez besoin',
    FeaturesSubtitle: 'Une suite complète d\'outils pour accompagner chaque étape de votre projet.',
    ReadyToStart: 'Prêt à commencer ?',
    ReadyToStartSub: 'Connectez-vous avec votre compte ESI pour accéder à votre espace.',
    LoginBtn: 'Se connecter',
    FooterText: 'ESI-GIT — École Supérieure d\'Informatique. Tous droits réservés.',
    Feature1Title: 'Gestion Git', Feature1Desc: 'Intégration native des dépôts Git pour chaque projet académique.',
    Feature2Title: 'Travail en Groupe', Feature2Desc: 'Créez et gérez vos groupes de projet facilement.',
    Feature3Title: 'Planification', Feature3Desc: 'Organisez des réunions avec l\'encadreur sans friction.',
    Feature4Title: 'Kanban Board', Feature4Desc: 'Suivez les tâches en temps réel avec un tableau Kanban intuitif.',
    Feature5Title: 'Suivi & Évaluation', Feature5Desc: 'Notation transparente et feedback structuré sur chaque livrable.',
    Feature6Title: 'Accès Sécurisé', Feature6Desc: 'Rôles distincts pour étudiants, encadreurs et administration.',

    // Extended Dashboard & Groups
    DashboardGreeting: 'Bonjour',
    TasksCompleted: 'Tâches complétées',
    PlannedMeetings: 'Réunions planifiées',
    OverallProgress: 'Avancement global',
    TeacherTasks: 'Tâches de l\'encadreur',
    ProjectProgress: 'Avancement du projet',
    InProgress: 'En progression',
    NotStarted: 'Pas encore démarré',
    RecentActivity: 'Activité récente',
    UpcomingDeadlines: 'Prochaines deadlines',
    MyGroup: 'Mon groupe',
    NoActivity: 'Aucune activité pour l\'instant',
    NoGroupDetails: 'Vous n\'avez pas encore de groupe',
    CreateJoinGroup: 'Créer / rejoindre un groupe',
    TaskOrigin: 'Origine des tâches',
    TaskStatus: 'État des tâches',
    Deliverables: 'Livrables',
    GroupTitle: 'Groupe',
    GroupSubtitle: 'Créez ou rejoignez un groupe de projet',
    CreateGroup: 'Créer',
    JoinGroup: 'Rejoindre',
    MyGroupTitle: 'Mon Groupe',
    MyGroupSub: 'Membres, rôles et dépôt de votre équipe',
    CurrentGroup: 'Groupe actuel',
    InviteCode: 'Code d\'invitation',
    Copy: 'Copier',
    Copied: 'Copié !',
    GithubRepo: 'Dépôt GitHub',
    Load: 'Charger',
    Open: 'Ouvrir',
    ChooseFile: 'Choisir un fichier',
    JuryAssigned: 'Jury Assigné',
    'JuryRoles.president': 'Président',
    'JuryRoles.examiner': 'Examinateur',
    'JuryRoles.supervisor': 'Encadreur',
    'JuryRoles.member': 'Membre',
    AssignJury: 'Assigner Jury',
    EditJury: 'Modifier Jury',
    NoJuryAssigned: 'Aucun jury assigné',
    WaitSupervisorValidation: 'Attente validation encadreur',
    ValidationRequestSub: 'Sélectionnez les membres du jury pour ce projet.',
    NoFile: 'Aucun document PDF uploadé',
    ProjectValidation: 'Validation du projet',
    SubmitProjectToSup: 'Soumettez votre projet à votre encadreur pour validation finale.',
    TeamMembers: 'Équipe',
    ChangeRole: 'Changer rôle',
    LeaveGroup: 'Quitter le groupe',

    // Teacher
    MyGroups: 'Mes groupes',
    GroupsSupervision: 'Groupes sous votre encadrement',
    NoGroupYet: 'Aucun groupe pour le moment.',
    ClickGroupDetails: 'Cliquez sur un groupe pour voir les détails',
    AllGroups: 'Tous les groupes',
    ValidationRequest: 'Demande de validation',
    ValidationRequestSub: 'Le groupe a soumis ce projet pour approbation finale. Veuillez vérifier les détails du projet et son dépôt GitHub avant de valider.',
    AssignTask: 'Assigner une tâche',
    ScheduleMeeting: 'Planifier une réunion',

    // Tasks Page
    TaskManagement: 'Gestion des tâches',
    TasksCompleted_Subtitle: 'tâches complétées',
    NewTask: 'Nouvelle tâche',
    GlobalProgress: 'Progression globale',
    DropHere: 'Déposer ici',
    CreateTask: 'Créer une tâche',
    TaskTitle: 'Titre de la tâche',
    Description: 'Description',
    Priority: 'Priorité',
    Column: 'Colonne',
    Tag: 'Tag / Catégorie',
    AssignMembers: 'Assigner des membres',
    High: 'Haute',
    Medium: 'Moyenne',
    Low: 'Basse',
    Todo: 'À faire',
    Hide: 'Masquer',
    Actions: 'Actions',
    Done: 'Terminé',
    InProgress_Short: 'En cours',

    // Teacher Groups
    SupervisionRequests: 'Demandes d\'encadrement',
    SupervisedGroups: 'Groupes Encadrés',
    NoPendingRequests: 'Aucune demande d\'encadrement en attente.',
    NoSupervisedGroups: 'Vous n\'avez aucun groupe encadré pour le moment.',
    ApproveRequest: 'Accepter',
    NewValidationRequest: 'Nouvelle demande de validation',
    NewValidationRequestSub: 'Ce groupe a soumis son projet pour validation finale.',
    LastCommits: 'Derniers Commits',
    Members: 'Membres du groupe',
    AssignTo: 'Assigner à',
    IfNoneSelected: 'Si aucun sélectionné → assignée à tous les membres',
    MeetingAutoAccepted: 'Les réunions planifiées par l\'encadreur sont automatiquement acceptées.',
    
    // Teacher Dashboard
    TeacherDashboard: 'Dashboard Encadreur',
    RealDataAnalytics: 'Analytiques calculées depuis les données réelles',
    SupervisedGroups_Stat: 'Groupes encadrés',
    ActiveGroups_Stat: 'Groupes actifs',
    AvgProgress_Stat: 'Avancement moyen',
    CompletionRate_Stat: 'Taux de complétion',
    PendingMeetings_Stat: 'Réunions en attente',
    PendingEvals_Stat: 'Évaluations en attente',
    ProgressByGroup: 'Avancement par groupe',
    TaskState: 'État des tâches',
    TasksByPriority: 'Tâches par priorité',
    NoGroups: 'Aucun groupe',
    FinalValidationRequests: 'Demandes de validation finale (Projets terminés)',
    ProjectSubmittedFinal: 'Projet soumis pour validation de fin d\'année',
    ValidateProject: 'Valider le projet',
    SendWithCorrections: 'Renvoyer avec corrections',

    // Jury
    DefenseJury: 'Jury de Soutenance',
    JuryParticipation: 'Soutenances auxquelles vous participez en tant que membre du jury',
    Assigned: 'Assignées',
    ToEvaluate: 'À évaluer',
    Evaluated: 'Évaluées',
    Scheduled: 'Planifiée',
    Evaluate: 'Évaluer',
    DefenseEvaluation: 'Évaluation du Jury',
    FinalGradeCalculated: 'Note finale calculée',
    EvaluationComments: 'Commentaires sur l\'évaluation',

    // Archive
    ArchiveTitle: 'Archive des Projets',
    ArchiveSubtitle: 'Projets de fin d\'études des années précédentes',
    AvgGrade: 'Moyenne',
    Mentions: 'Mentions',
    Years: 'Années',
    FilterBy: 'Filtrer par',
    CurrentSupervisor: 'Encadreur Actuel',
    ManageSupervision: 'Gérez l\'encadrement de votre projet PFE',
    RequestNewSupervisor: 'Solliciter un nouvel encadreur',
    NoSupervisorAssigned: 'Aucun encadreur assigné pour le moment.',
    PendingRequest: 'Demande en attente',
    PendingRequestMsg: 'Vous avez déjà une demande en cours. Vous devez attendre la réponse ou qu\'elle soit refusée avant d\'en envoyer une autre.',
    RequestHistory: 'Historique des demandes',
    NoRequestsSent: 'Aucune demande envoyée.',
    Blocked: 'Bloqué',
    Block: 'Bloquer',
    Unblock: 'Débloquer',
    CyclePrepa: 'Cycle Préparatoire',
    CycleSuperieur: 'Cycle Supérieur',
    Department: 'Département',
    Blocked: 'Bloqué',
    Accepted: 'Accepté',
    RequestSent: 'Demande envoyée !',
    SendRequest: 'Envoyer la demande',
    ConfirmSend: 'Confirmer l\'envoi',
    AccompanyingMessage: 'Message d\'accompagnement (Optionnel)',
    ExplainSubject: 'Expliquez brièvement votre sujet de PFE...',
    SearchByTeacherName: 'Rechercher par nom ou spécialité...',
    OfficialSupervisor: 'Encadreur officiel du projet',
    YearFilter: 'Année',
    Supervisor: 'Encadreur',
    All: 'Tous',
    Validated: 'Validé',

    // Admin
    AdminDashboard: 'Dashboard Admin',
    RealTimeAnalytics: 'Analytiques en temps réel — données calculées depuis la base',
    TotalStudents_Stat: 'Total étudiants',
    Teachers_Stat: 'Enseignants',
    ArchivedProjects_Stat: 'Projets archivés',
    AvgProgressBySupervisor: 'Avancement moyen par encadreur',
    WeightedAvgProgress: 'Progression moyenne pondérée',
    UserDistribution: 'Répartition utilisateurs',
    Admins: 'Admins',
    GroupsPerSpecialty: 'Groupes par spécialité',
    ProjectState: 'État des projets',
    TotalTasks_Stat: 'Total tâches',
    AssignedBySupervisor: 'Assignées par encadreur',
    CreatedByStudents: 'Créées par étudiants',
    OverallAverage: 'Moyenne générale',
    Mentions_Stat: 'Mentions',
    NoGroupAssigned: 'Aucun groupe encore assigné',

    // User Management
    UserManagement: 'Utilisateurs',
    AddUser: 'Ajouter utilisateur',
    EditUser: 'Modifier utilisateur',
    DeleteUser: 'Supprimer utilisateur',
    UserDetail: 'Détail utilisateur',
    Identity: 'Identité',
    StudentInfo: 'Informations étudiant',
    TeacherInfo: 'Informations enseignant',
    AssignStudent: 'Assigner étudiant',
    AvailableForSupervision: 'Disponible pour encadrement',
    Department: 'Département',
    TeachingSpecialty: 'Spécialité d\'enseignement',
    Displaying: 'Affichage de',
    To: 'à',
    Of: 'sur',
    ConfirmDeleteUser: 'Êtes-vous sûr de vouloir supprimer cet utilisateur ? Cette action est irréversible.',
    
    // Group Management (Admin)
    AssignJury: 'Assigner le jury',
    EditJury: 'Modifier le jury',
    JuryAssigned: 'Jury assigné',
    NoJuryAssigned: 'Aucun jury assigné pour ce groupe.',
    GroupDetail: 'Détail du groupe',
    TotalGroups_Stat: 'Total groupes',
    Active_Stat: 'Actif',
    NonApproved_Stat: 'Non approuvé',
    StudentsWithoutGroup: 'Étudiants sans groupe',
    CreateGroupTitle: 'Créer un nouveau groupe',
    ProjectTitle: 'Titre du projet',
    GroupCode: 'Code du groupe',
    GroupManagement: 'Gestion des groupes',
    AllStudentsInGroup: 'Tous les étudiants ont un groupe',
    JuryRoles: {
      president: 'Président',
      member: 'Examinateur',
      supervisor: 'Encadreur'
    },

    // Profil
    ProfileTitle: 'Profil',
    ProfileSubtitle: 'Vos informations personnelles',
    PersonalInfo: 'Informations personnelles',
    FullName: 'Nom complet',
    Email: 'Adresse e-mail',
    Specialty: 'Spécialité',
    Promotion: 'Promotion',
    L1: '1ère Année (L1)',
    L2: '2ème Année (L2)',
    L3: '3ème Année (L3)',
    M1: 'Master 1 (M1)',
    M2: 'Master 2 (M2)',
    AdminLock: '🔒 Les informations du profil sont gérées par l\'administration. Contactez votre gestionnaire pour toute modification.',
    SwitchToTeacher: 'Passer en mode Enseignant',
    SwitchToAdmin: 'Passer en mode Administrateur',
    BackToTop: 'Retour en haut',
    Notifications: 'Notifications',
    ActiveProjects: 'Projets actifs',
    SubmissionsThisMonth: 'Soumissions ce mois',
    AvgCompletionRate: 'Taux de complétion moyen',
    HideArchiveStudent: 'Masquer l\'Archive (Étudiants)',
    HideArchiveStudent_Desc: 'Les étudiants ne pourront plus voir l\'archive des projets.',
    HideJuryTeacher: 'Masquer les Jurys (Enseignants)',
    HideJuryTeacher_Desc: 'Les enseignants ne pourront plus accéder à l\'évaluation des jurys.',

    // Missing keys added
    GroupName: 'Nom du groupe',
    ProjectTheme: 'Thème du projet',
    Role: 'Rôle',
    StatusUpdated: 'Statut mis à jour',
    FirstName: 'Prénom',
    LastName: 'Nom de famille',
    AcademicYear: 'Année académique',
    Level: 'Niveau',
    Groups_Stat: 'Groupes',
    NoData: 'Aucune donnée disponible',
    ProjectType: 'Type de projet',
    ProjectDescription: 'Description du projet',
    CreateProject: 'Créer un projet',
    SupervisorAvailability: 'Disponibilité',
    Available: 'Disponible',
    Unavailable: 'Indisponible',
    PasswordChanged: 'Mot de passe modifié avec succès',
    PasswordError: 'Erreur lors du changement de mot de passe',
    OldPassword: 'Ancien mot de passe',
    NewPassword: 'Nouveau mot de passe',
    ConfirmPassword: 'Confirmer le mot de passe',
    ChangePassword: 'Changer le mot de passe',
    BlockUser: 'Bloquer',
    UnblockUser: 'Débloquer',
    ResetPassword: 'Réinitialiser le mot de passe',

    // Admin Analytics & Settings
    PlatformAnalytics: 'Analyses de la plateforme',
    ConsolidatedData: 'Données consolidées',
    ExportCSV: 'Exporter Rapport (CSV)',
    SuccessRate: 'Taux de réussite',
    StudentsAtRisk: 'Étudiants à risque',
    GradeTrends: 'Tendances des notes',
    StudentActivity: 'Activité des étudiants',
    NotationPatterns: 'Patterns de notation (Enseignants)',
    UsageTrends: 'Tendances d\'utilisation',
    AcademicYears: 'Années académiques',
    ActiveYear: 'Année active',
    ActivePromos: 'Promotions actives',
    AddPromo: 'Ajouter promotion',
    ChangeYearWarning: '⚠️ Changer l\'année active archivera automatiquement tous les projets en cours.',
    SpecialtiesThemes: 'Spécialités & Thèmes',
    GradingFormula: 'Formule de calcul des moyennes',
    FormulaList: 'Formules existantes',
    ActiveStatus: 'ACTIVE',
    VisibilityAccess: 'Visibilité & Accès',
    ShowArchiveStudents: 'Afficher l\'archive aux étudiants',
    ShowArchiveStudents_Desc: 'Permet aux étudiants de consulter les anciens projets.',
    NewFormula: 'Nouvelle formule',
    Expression: 'Expression',
    
    // Admin Users Extra
    NewPasswordOptional: 'Nouveau Password (optionnel)',
    LeaveEmptyNoChange: 'Laisser vide pour ne pas changer',
    Choose: 'Choisir',
    ImportUsers: 'Importer des utilisateurs',
    StaffMembers: 'Enseignants / Staff',
    AccountsCreated: 'Comptes créés avec succès',
    StaffNote: 'Note: Un utilisateur Staff peut être à la fois Enseignant et Admin.',
    DragDropFile: 'Glissez votre fichier ici',
    Browse: 'parcourir',
    ImportInProgress: 'Import en cours...',
    Imported: 'utilisateur(s) importé(s) !',
    RowsIgnored: 'ligne(s) ignorée(s)',
    Summary: 'Résumé',
    StudentList: 'Liste des étudiants',
    Grade: 'Note'
  },
  en: {
    // Nav / Sidebar
    Dashboard: 'Dashboard',
    Projects: 'Projects',
    Archive: 'Archive',
    Groups: 'Groups',
    Students: 'Students',
    Teachers: 'Teachers',
    Admin: 'Administration',
    Users: 'Users',
    Supervision: 'Supervision',
    Juries: 'Juries',
    MyProject: 'My Project',
    Tasks: 'Tasks',
    Meetings: 'Meetings',
    Profile: 'Profile',
    Evaluations: 'Evaluations',
    Year: 'Study Year',
    Settings: 'Settings',
    Logout: 'Logout',
    Requests: 'Requests',

    // Common phrases
    Search: 'Search...',
    Save: 'Save',
    Cancel: 'Cancel',
    Delete: 'Delete',
    Edit: 'Edit',
    Submit: 'Submit',
    Approve: 'Approve',
    Reject: 'Reject',
    Status: 'Status',
    Date: 'Date',
    Loading: 'Loading...',
    Error: 'Error',
    Success: 'Success',
    Confirm: 'Confirm',

    // Home Page
    HomeTitle: 'Manage your academic projects with',
    HomeSubtitle: 'The all-in-one platform for ESI students, supervisors, and administration. Collaborate, code, and succeed.',
    HomeBadge: '🎓 University Platform',
    GetStarted: 'Get Started',
    LearnMore: 'Learn More',
    StatsActiveStudents: 'Active Students',
    StatsProjects: 'Managed Projects',
    StatsTeachers: 'Supervisors',
    StatsUptime: 'System Uptime',
    FeaturesTitle: 'Everything you need',
    FeaturesSubtitle: 'A complete suite of tools to support every stage of your graduation project.',
    ReadyToStart: 'Ready to start?',
    ReadyToStartSub: 'Log in with your ESI account to access your workspace.',
    LoginBtn: 'Log In',
    FooterText: 'ESI-GIT — Higher School of Computer Science. All rights reserved.',
    Feature1Title: 'Git Management', Feature1Desc: 'Native Git repository integration for every academic project.',
    Feature2Title: 'Teamwork', Feature2Desc: 'Easily create and manage your project groups.',
    Feature3Title: 'Scheduling', Feature3Desc: 'Organize meetings with your supervisor seamlessly.',
    Feature4Title: 'Kanban Board', Feature4Desc: 'Track tasks in real time with an intuitive Kanban board.',
    Feature5Title: 'Tracking & Grading', Feature5Desc: 'Transparent grading and structured feedback on each deliverable.',
    Feature6Title: 'Secure Access', Feature6Desc: 'Distinct roles for students, supervisors, and administration.',

    // Extended Dashboard & Groups
    DashboardGreeting: 'Hello',
    TasksCompleted: 'Tasks completed',
    PlannedMeetings: 'Planned meetings',
    OverallProgress: 'Overall progress',
    TeacherTasks: 'Supervisor tasks',
    ProjectProgress: 'Project progress',
    InProgress: 'In progress',
    NotStarted: 'Not started yet',
    RecentActivity: 'Recent activity',
    UpcomingDeadlines: 'Upcoming deadlines',
    MyGroup: 'My group',
    NoActivity: 'No activity for now',
    NoGroupDetails: 'You do not have a group yet',
    CreateJoinGroup: 'Create / join a group',
    TaskOrigin: 'Task origin',
    TaskStatus: 'Task status',
    Deliverables: 'Deliverables',
    GroupTitle: 'Group',
    GroupSubtitle: 'Create or join a project group',
    CreateGroup: 'Create',
    JoinGroup: 'Join',
    MyGroupTitle: 'My Group',
    MyGroupSub: 'Members, roles and repository of your team',
    CurrentGroup: 'Current group',
    InviteCode: 'Invitation code',
    Copy: 'Copy',
    Copied: 'Copied !',
    GithubRepo: 'GitHub Repository',
    Load: 'Load',
    Open: 'Open',
    ChooseFile: 'Choose file',
    JuryAssigned: 'Jury Assigned',
    'JuryRoles.president': 'President',
    'JuryRoles.examiner': 'Examiner',
    'JuryRoles.supervisor': 'Supervisor',
    'JuryRoles.member': 'Member',
    AssignJury: 'Assign Jury',
    EditJury: 'Edit Jury',
    NoJuryAssigned: 'No jury assigned',
    WaitSupervisorValidation: 'Waiting for supervisor validation',
    ValidationRequestSub: 'Select the jury members for this project.',
    NoFile: 'No PDF document uploaded',
    ProjectValidation: 'Project validation',
    SubmitProjectToSup: 'Submit your project to your supervisor for final validation.',
    TeamMembers: 'Team',
    ChangeRole: 'Change role',
    LeaveGroup: 'Leave group',

    // Teacher
    MyGroups: 'My groups',
    GroupsSupervision: 'Groups under your supervision',
    NoGroupYet: 'No group at the moment.',
    ClickGroupDetails: 'Click on a group to see details',
    AllGroups: 'All groups',
    ValidationRequest: 'Validation request',
    AssignTask: 'Assign a task',
    ScheduleMeeting: 'Schedule a meeting',

    // Tasks Page
    TaskManagement: 'Task Management',
    TasksCompleted_Subtitle: 'tasks completed',
    NewTask: 'New Task',
    GlobalProgress: 'Global Progress',
    DropHere: 'Drop here',
    CreateTask: 'Create a Task',
    TaskTitle: 'Task Title',
    Description: 'Description',
    Priority: 'Priority',
    Column: 'Column',
    Tag: 'Tag / Category',
    AssignMembers: 'Assign Members',
    High: 'High',
    Medium: 'Medium',
    Low: 'Low',
    Todo: 'To Do',
    Hide: 'Hide',
    Actions: 'Actions',
    Done: 'Done',
    InProgress_Short: 'In Progress',

    // Teacher Groups
    SupervisionRequests: 'Supervision Requests',
    SupervisedGroups: 'Supervised Groups',
    NoPendingRequests: 'No pending supervision requests.',
    NoSupervisedGroups: 'You have no supervised groups at the moment.',
    ApproveRequest: 'Accept',
    NewValidationRequest: 'New Validation Request',
    NewValidationRequestSub: 'This group has submitted their project for final validation.',
    LastCommits: 'Last Commits',
    Members: 'Group Members',
    AssignTo: 'Assign to',
    IfNoneSelected: 'If none selected → assigned to all members',
    MeetingAutoAccepted: 'Meetings scheduled by the supervisor are automatically accepted.',

    // Teacher Dashboard
    TeacherDashboard: 'Supervisor Dashboard',
    RealDataAnalytics: 'Analytics calculated from real data',
    SupervisedGroups_Stat: 'Supervised Groups',
    ActiveGroups_Stat: 'Active Groups',
    AvgProgress_Stat: 'Average Progress',
    CompletionRate_Stat: 'Completion Rate',
    PendingMeetings_Stat: 'Pending Meetings',
    PendingEvals_Stat: 'Pending Evaluations',
    ProgressByGroup: 'Progress by Group',
    TaskState: 'Task State',
    TasksByPriority: 'Tasks by Priority',
    NoGroups: 'No Groups',
    FinalValidationRequests: 'Final Validation Requests (Completed Projects)',
    ProjectSubmittedFinal: 'Project submitted for end-of-year validation',
    ValidateProject: 'Validate Project',
    SendWithCorrections: 'Send with Corrections',

    // Jury
    DefenseJury: 'Defense Jury',
    JuryParticipation: 'Defenses in which you participate as a jury member',
    Assigned: 'Assigned',
    ToEvaluate: 'To Evaluate',
    Evaluated: 'Evaluated',
    Scheduled: 'Scheduled',
    Evaluate: 'Evaluate',
    DefenseEvaluation: 'Jury Evaluation',
    FinalGradeCalculated: 'Final grade calculated',
    EvaluationComments: 'Evaluation comments',

    // Archive
    ArchiveTitle: 'Project Archive',
    ArchiveSubtitle: 'Final year projects from previous years',
    AvgGrade: 'Average',
    Mentions: 'Mentions',
    Years: 'Years',
    FilterBy: 'Filter By',
    CurrentSupervisor: 'Current Supervisor',
    ManageSupervision: 'Manage your project supervision',
    RequestNewSupervisor: 'Request a new supervisor',
    NoSupervisorAssigned: 'No supervisor assigned yet.',
    PendingRequest: 'Pending Request',
    PendingRequestMsg: 'You already have a pending request. You must wait for a response before sending another one.',
    RequestHistory: 'Request History',
    NoRequestsSent: 'No requests sent.',
    Wait: 'Wait',
    Rejected: 'Rejected',
    Accepted: 'Accepted',
    RequestSent: 'Request sent!',
    SendRequest: 'Send Request',
    ConfirmSend: 'Confirm Sending',
    AccompanyingMessage: 'Accompanying Message (Optional)',
    ExplainSubject: 'Briefly explain your project subject...',
    SearchByTeacherName: 'Search by name or specialty...',
    OfficialSupervisor: 'Official project supervisor',
    YearFilter: 'Year',
    Supervisor: 'Supervisor',
    All: 'All',
    Validated: 'Validated',

    // Admin
    AdminDashboard: 'Admin Dashboard',
    RealTimeAnalytics: 'Real-time analytics — data calculated from base',
    TotalStudents_Stat: 'Total students',
    Teachers_Stat: 'Teachers',
    ArchivedProjects_Stat: 'Archived Projects',
    AvgProgressBySupervisor: 'Average progress by supervisor',
    WeightedAvgProgress: 'Weighted average progress',
    UserDistribution: 'User distribution',
    Admins: 'Admins',
    GroupsPerSpecialty: 'Groups per specialty',
    ProjectState: 'Project state',
    TotalTasks_Stat: 'Total tasks',
    AssignedBySupervisor: 'Assigned by supervisor',
    CreatedByStudents: 'Created by students',
    OverallAverage: 'Overall average',
    Mentions_Stat: 'Mentions',
    NoGroupAssigned: 'No group assigned yet',

    // User Management
    UserManagement: 'Users',
    AddUser: 'Add User',
    EditUser: 'Edit User',
    DeleteUser: 'Delete User',
    UserDetail: 'User Detail',
    Identity: 'Identity',
    StudentInfo: 'Student Information',
    TeacherInfo: 'Teacher Information',
    AssignStudent: 'Assign Student',
    AvailableForSupervision: 'Available for supervision',
    Department: 'Department',
    TeachingSpecialty: 'Teaching Specialty',
    Displaying: 'Showing',
    To: 'to',
    Of: 'of',
    ConfirmDeleteUser: 'Are you sure you want to delete this user? This action is irreversible.',

    // Group Management (Admin)
    GroupDetail: 'Group Detail',
    TotalGroups_Stat: 'Total groups',
    Active_Stat: 'Active',
    NonApproved_Stat: 'Non approved',
    StudentsWithoutGroup: 'Students without group',
    CreateGroupTitle: 'Create New Group',
    ProjectTitle: 'Project Title',
    GroupCode: 'Group Code',
    GroupManagement: 'Group management',
    AllStudentsInGroup: 'All students have a group',

    // Profil
    ProfileTitle: 'Profile',
    ProfileSubtitle: 'Your personal information',
    PersonalInfo: 'Personal Information',
    FullName: 'Full Name',
    Email: 'Email Address',
    Specialty: 'Specialty',
    Promotion: 'Promotion',
    L1: '1st Year (L1)',
    L2: '2nd Year (L2)',
    L3: '3rd Year (L3)',
    M1: 'Master 1 (M1)',
    M2: 'Master 2 (M2)',
    AdminLock: '🔒 Profile information is managed by administration. Contact your manager for any modification.',
    SwitchToTeacher: 'Switch to Teacher Mode',
    SwitchToAdmin: 'Switch to Admin Mode',
    BackToTop: 'Scroll to top',
    Notifications: 'Notifications',
    ActiveProjects: 'Active Projects',
    SubmissionsThisMonth: 'Submissions this month',
    AvgCompletionRate: 'Average Completion Rate',
    HideArchiveStudent: 'Hide Archive (Students)',
    HideArchiveStudent_Desc: 'Students will no longer be able to see the project archive.',
    HideJuryTeacher: 'Hide Juries (Teachers)',
    HideJuryTeacher_Desc: 'Teachers will no longer be able to access jury evaluations.',

    // Missing keys added
    GroupName: 'Group Name',
    ProjectTheme: 'Project Theme',
    Role: 'Role',
    StatusUpdated: 'Status updated',
    FirstName: 'First Name',
    LastName: 'Last Name',
    AcademicYear: 'Academic Year',
    Level: 'Level',
    Groups_Stat: 'Groups',
    NoData: 'No data available',
    ProjectType: 'Project Type',
    ProjectDescription: 'Project Description',
    CreateProject: 'Create a project',
    SupervisorAvailability: 'Availability',
    Blocked: 'Blocked',
    Block: 'Block',
    Unblock: 'Unblock',
    CyclePrepa: 'Preparatory Cycle',
    CycleSuperieur: 'Superior Cycle',
    Department: 'Department',
    PasswordChanged: 'Password changed successfully',
    PasswordError: 'Error changing password',
    OldPassword: 'Old password',
    NewPassword: 'New password',
    ConfirmPassword: 'Confirm password',
    ChangePassword: 'Change Password',
    BlockUser: 'Block',
    UnblockUser: 'Unblock',
    ResetPassword: 'Reset Password',

    // Admin Analytics & Settings
    PlatformAnalytics: 'Platform Analytics',
    ConsolidatedData: 'Consolidated Data',
    ExportCSV: 'Export Report (CSV)',
    SuccessRate: 'Success Rate',
    StudentsAtRisk: 'Students at Risk',
    GradeTrends: 'Grade Trends',
    StudentActivity: 'Student Activity',
    NotationPatterns: 'Grading Patterns (Teachers)',
    UsageTrends: 'Usage Trends',
    AcademicYears: 'Academic Years',
    ActiveYear: 'Active Year',
    ActivePromos: 'Active Promotions',
    AddPromo: 'Add Promotion',
    ChangeYearWarning: '⚠️ Changing the active year will automatically archive all current projects.',
    SpecialtiesThemes: 'Specialties & Themes',
    GradingFormula: 'Grading Formula',
    FormulaList: 'Existing Formulas',
    ActiveStatus: 'ACTIVE',
    VisibilityAccess: 'Visibility & Access',
    ShowArchiveStudents: 'Show archive to students',
    ShowArchiveStudents_Desc: 'Allows students to view previous projects.',
    NewFormula: 'New Formula',
    Expression: 'Expression',

    // Admin Users Extra
    NewPasswordOptional: 'New Password (optional)',
    LeaveEmptyNoChange: 'Leave empty for no change',
    Choose: 'Choose',
    ImportUsers: 'Import Users',
    StaffMembers: 'Teachers / Staff',
    AccountsCreated: 'Accounts created successfully',
    StaffNote: 'Note: A Staff user can be both Teacher and Admin.',
    DragDropFile: 'Drag your file here',
    Browse: 'browse',
    ImportInProgress: 'Import in progress...',
    Imported: 'user(s) imported!',
    RowsIgnored: 'row(s) ignored',
    Summary: 'Summary',
    StudentList: 'Student List',
    Grade: 'Grade'
  }
};

export function LanguageProvider({ children }) {
  const [lang, setLang] = useState('fr');

  useEffect(() => {
    const saved = localStorage.getItem('appLang');
    if (saved && (saved === 'fr' || saved === 'en')) {
      setLang(saved);
      document.documentElement.lang = saved;
    } else {
      document.documentElement.lang = 'fr';
    }
  }, []);

  const toggleLanguage = () => {
    const nextLang = lang === 'fr' ? 'en' : 'fr';
    setLang(nextLang);
    localStorage.setItem('appLang', nextLang);
    document.documentElement.lang = nextLang;
  };

  const t = (key) => {
    if (!translations[lang]) return key;
    return translations[lang][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ lang, toggleLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  return useContext(LanguageContext);
}
