# Generated by Django 6.0.3 on 2026-04-30 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectAttachment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('file', models.FileField(upload_to='project_attachments/%Y/%m/')),
                ('filename', models.CharField(max_length=255)),
                ('file_size', models.IntegerField(blank=True, null=True)),
                ('attachment_type', models.CharField(choices=[('report', 'Project Report'), ('presentation', 'Presentation Slides'), ('deliverable', 'Project Deliverable'), ('documentation', 'Documentation'), ('other', 'Other')], default='other', max_length=20)),
                ('title', models.CharField(blank=True, max_length=200)),
                ('description', models.TextField(blank=True)),
                ('version', models.CharField(blank=True, max_length=20)),
                ('is_final', models.BooleanField(default=False)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'project_attachments',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('PID', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('type', models.CharField(max_length=50)),
                ('specialty', models.CharField(blank=True, max_length=100, null=True)),
                ('year', models.CharField(blank=True, max_length=9, null=True)),
                ('academic_level', models.IntegerField(blank=True, null=True)),
                ('github_url', models.URLField(blank=True, max_length=300, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('creation_date', models.DateField(auto_now_add=True)),
                ('finish_date', models.DateField(blank=True, null=True)),
                ('archived', models.BooleanField(default=False)),
                ('invite_code', models.CharField(max_length=8, unique=True)),
                ('submitted_to_supervisor', models.BooleanField(default=False)),
                ('supervisor_feedback', models.TextField(blank=True, null=True)),
                ('final_submission_approved', models.BooleanField(default=False)),
                ('final_submission_date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SProjects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('frontend', 'Frontend'), ('backend', 'Backend'), ('design', 'Design'), ('fullstack', 'Fullstack')], max_length=20)),
                ('is_leader', models.BooleanField(default=False)),
                ('joined_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Student Project',
                'verbose_name_plural': 'Student Projects',
                'db_table': 'sprojects',
            },
        ),
        migrations.CreateModel(
            name='SupervisorRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'supervisor_requests',
            },
        ),
    ]
