# Generated by Django 6.0.3 on 2026-05-01 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='is_public',
            field=models.BooleanField(default=True),
        ),
    ]
