# Generated by Django 6.0.3 on 2026-04-28 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='submitted_to_supervisor',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='projects',
            name='supervisor_feedback',
            field=models.TextField(blank=True, null=True),
        ),
    ]
