# Generated by Django 6.0.3 on 2026-05-26 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projects',
            name='final_submission_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='projects',
            name='final_submission_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projects',
            name='is_public',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='projects',
            name='submitted_to_supervisor',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='projects',
            name='supervisor_feedback',
            field=models.TextField(blank=True, null=True),
        ),
    ]
