# Generated by Django 6.0.3 on 2026-04-29 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_projects_submitted_to_supervisor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='final_submission_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='projects',
            name='final_submission_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
