# Generated by Django 6.0.3 on 2026-05-31 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_projects_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='tech_stack',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
