# Generated by Django 6.0.3 on 2026-06-09 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_alter_projects_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='confirmed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projects',
            name='is_confirmed',
            field=models.BooleanField(default=False),
        ),
    ]
