# Generated by Django 6.0.3 on 2026-06-10 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_add_group_lock_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supervisorrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('admin_assigned', 'Admin Assigned')], default='pending', max_length=15),
        ),
    ]
