# Generated by Django 6.0.3 on 2026-04-27 13:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grades',
            fields=[
                ('PID', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='projects.projects')),
                ('grade1', models.FloatField(blank=True, null=True)),
                ('grade2', models.FloatField(blank=True, null=True)),
                ('grade3', models.FloatField(blank=True, null=True)),
                ('final_grade', models.FloatField(blank=True, null=True)),
                ('comments', models.TextField(blank=True)),
            ],
            options={
                'verbose_name_plural': 'Grades',
                'db_table': 'grades',
            },
        ),
        migrations.CreateModel(
            name='GradingFormula',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('formula_expression', models.TextField()),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'grading_formulas',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProjectJury',
            fields=[
                ('PID', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='projects.projects')),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Project Juries',
                'db_table': 'project_jury',
            },
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('presentation_date', models.DateField()),
                ('presentation_time', models.TimeField()),
                ('room', models.CharField(max_length=50)),
                ('duration_minutes', models.IntegerField(default=30)),
            ],
            options={
                'db_table': 'schedules',
            },
        ),
    ]
