# Generated by Django 6.0.3 on 2026-04-27 13:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('jury', '0001_initial'),
        ('projects', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gradingformula',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.staff'),
        ),
        migrations.AddField(
            model_name='projectjury',
            name='teacher1_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jury_as_president', to='users.staff'),
        ),
        migrations.AddField(
            model_name='projectjury',
            name='teacher2_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jury_as_examiner1', to='users.staff'),
        ),
        migrations.AddField(
            model_name='projectjury',
            name='teacher3_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jury_as_examiner2', to='users.staff'),
        ),
        migrations.AddField(
            model_name='schedule',
            name='PID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.projects'),
        ),
        migrations.AlterUniqueTogether(
            name='schedule',
            unique_together={('presentation_date', 'presentation_time', 'room')},
        ),
    ]
