# Generated by Django 6.0.3 on 2026-05-06 18:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jury', '0002_initial'),
        ('users', '0003_student_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='grades',
            name='grade4',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projectjury',
            name='supervisor_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jury_as_supervisor', to='users.staff'),
        ),
    ]
