# Generated by Django 6.0.3 on 2026-05-26 21:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jury', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gradingformula',
            old_name='formula_expression',
            new_name='expression',
        ),
        migrations.RemoveField(
            model_name='grades',
            name='grade1',
        ),
        migrations.RemoveField(
            model_name='grades',
            name='grade2',
        ),
        migrations.RemoveField(
            model_name='grades',
            name='grade3',
        ),
        migrations.AddField(
            model_name='grades',
            name='formula',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='jury.gradingformula'),
        ),
        migrations.AddField(
            model_name='grades',
            name='formula_snapshot',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='grades',
            name='graded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='grades',
            name='values',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='gradingformula',
            name='labels',
            field=models.JSONField(default=dict),
        ),
    ]
