# Generated by Django 6.0.3 on 2026-06-05 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jury', '0003_rename_formula_expression_gradingformula_expression_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='department_name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
