# Generated by Django 6.0.3 on 2026-05-30 13:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jury', '0003_grades_grade4_projectjury_supervisor_id'),
        ('users', '0003_student_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectjury',
            name='teacher3_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jury_as_examiner2', to='users.staff'),
        ),
    ]
