# Generated by Django 6.0.3 on 2026-06-06 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jury', '0004_schedule_department_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='duration_minutes',
            field=models.IntegerField(default=60),
        ),
    ]
