# Generated by Django 6.0.3 on 2026-05-30 14:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jury', '0004_alter_projectjury_teacher3_id'),
        ('users', '0003_student_department'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grades',
            name='grade3',
        ),
        migrations.RemoveField(
            model_name='projectjury',
            name='teacher3_id',
        ),
        migrations.AddField(
            model_name='projectjury',
            name='presentation_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projectjury',
            name='presentation_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projectjury',
            name='room',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='projectjury',
            name='teacher2_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jury_as_examiner', to='users.staff'),
        ),
    ]
