# Generated by Django 6.0.3 on 2026-04-29 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_staff_department_staff_specialty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='TID',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
