# Generated by Django 6.0.3 on 2026-06-06 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_staff_department_alter_staff_specialty_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='CID',
            field=models.BigIntegerField(primary_key=True, serialize=False),
        ),
    ]
