# Generated by Django 6.0.3 on 2026-04-30 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='platformsettings',
            name='current_academic_year',
            field=models.CharField(default='2024-2025', max_length=20),
        ),
    ]
