# Generated by Django 6.0.3 on 2026-05-26 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='platformsettings',
            name='contact_email',
            field=models.CharField(default='contact@esi.dz', max_length=100),
        ),
        migrations.AddField(
            model_name='platformsettings',
            name='current_academic_year',
            field=models.CharField(default='2024-2025', max_length=20),
        ),
        migrations.AddField(
            model_name='platformsettings',
            name='project_types',
            field=models.TextField(default='PFE,Stage,Projet'),
        ),
        migrations.AddField(
            model_name='platformsettings',
            name='students_can_see_jury_column',
            field=models.BooleanField(default=False),
        ),
    ]
