# Generated by Django 6.0.3 on 2026-05-06 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0003_platformsettings_current_academic_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='platformsettings',
            name='project_types',
            field=models.TextField(default='PFE,Stage,Projet'),
        ),
    ]
