# Generated by Django 6.0.3 on 2026-05-31 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0003_platformsettings_contact_email_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='platformsettings',
            old_name='students_can_see_jury_column',
            new_name='jury_page_visible',
        ),
    ]
