# Generated by Django 6.0.3 on 2026-05-06 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0004_platformsettings_project_types'),
    ]

    operations = [
        migrations.AddField(
            model_name='platformsettings',
            name='demo_weight',
            field=models.IntegerField(default=50),
        ),
        migrations.AddField(
            model_name='platformsettings',
            name='document_weight',
            field=models.IntegerField(default=30),
        ),
        migrations.AddField(
            model_name='platformsettings',
            name='presentation_weight',
            field=models.IntegerField(default=20),
        ),
    ]
