# Generated by Django 6.0.3 on 2026-05-31 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0004_rename_students_can_see_jury_column_platformsettings_jury_page_visible'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='department',
            name='name',
        ),
        migrations.RemoveField(
            model_name='platformsettings',
            name='project_types',
        ),
        migrations.AddField(
            model_name='department',
            name='cycle',
            field=models.CharField(choices=[('PREP', 'Preparatory Cycle'), ('SUP', 'Superior Cycle')], default='PREP', max_length=10, unique=True),
        ),
        migrations.AddField(
            model_name='specialty',
            name='full_name',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='specialty',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
