# Generated by Django 6.0.3 on 2026-05-19 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0005_platformsettings_demo_weight_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='platformsettings',
            name='other_weight',
            field=models.IntegerField(default=20),
        ),
        migrations.AddField(
            model_name='platformsettings',
            name='president_weight',
            field=models.IntegerField(default=40),
        ),
        migrations.AddField(
            model_name='platformsettings',
            name='students_can_see_jury_column',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='platformsettings',
            name='supervisor_weight',
            field=models.IntegerField(default=40),
        ),
    ]
