# Generated by Django 6.0.3 on 2026-06-05 20:38

import admin_panel.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0005_remove_department_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='platformsettings',
            name='contact_email',
            field=models.CharField(default='egit@esi-sba.dz', max_length=100),
        ),
        migrations.AlterField(
            model_name='platformsettings',
            name='current_academic_year',
            field=models.CharField(default=admin_panel.models._current_academic_year, max_length=20),
        ),
    ]
