# Generated by Django 6.0.3 on 2026-05-19 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0006_platformsettings_other_weight_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='platformsettings',
            name='contact_email',
            field=models.CharField(default='aced@esi.dz', max_length=100),
        ),
    ]
