# Generated by Django 6.0.3 on 2026-06-06 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0006_alter_platformsettings_contact_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='platformsettings',
            name='students_can_see_attachments',
            field=models.BooleanField(default=False),
        ),
    ]
