# Generated by Django 6.0.3 on 2026-06-09 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0007_platformsettings_students_can_see_attachments'),
    ]

    operations = [
        migrations.AddField(
            model_name='platformsettings',
            name='all_graded_notified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='platformsettings',
            name='graded_notified_levels',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='platformsettings',
            name='group_lock_deadline',
            field=models.DateField(blank=True, null=True),
        ),
    ]
