# Generated by Django 6.0.3 on 2026-05-28 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0007_platformsettings_contact_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='platformsettings',
            name='hide_jury_from_jury',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='platformsettings',
            name='hide_jury_page_no_assignment',
            field=models.BooleanField(default=False),
        ),
    ]
