# Generated by Django 6.0.3 on 2026-05-30 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0008_platformsettings_hide_jury_from_jury_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='platformsettings',
            name='hide_jury_page_no_assignment',
        ),
        migrations.AddField(
            model_name='platformsettings',
            name='evaluation_criteria',
            field=models.TextField(default='{"president": [{"name": "Produit final", "weight": 25}, {"name": "Manuel d\'installation et d\'utilisation", "weight": 25}, {"name": "Soutenance", "weight": 25}, {"name": "Rapport", "weight": 25}], "supervisor": [{"name": "Travail continu", "weight": 50}, {"name": "Soutenance", "weight": 50}], "examiner": [{"name": "Soutenance", "weight": 100}]}'),
        ),
    ]
